import { Teacher, Room, CalendarEvent, GanttBlock, Classification, AppSettings, ListsState, PositionAssignment, RateCard } from './types';

export const COLORS = [
  '#3b82f6', // blue
  '#ef4444', // red
  '#10b981', // green
  '#f59e0b', // amber
  '#8b5cf6', // violet
  '#ec4899', // pink
  '#6366f1', // indigo
  '#14b8a6', // teal
  '#f97316', // orange
  '#64748b', // slate
];

// --- Migration helper: ensure old teacher data gets positionAssignments ---
export const migrateTeacher = (t: any): Teacher => {
  // If positionAssignments already exists and has data, just ensure positions is synced
  if (t.positionAssignments && t.positionAssignments.length > 0) {
    return {
      ...t,
      tags: t.tags || [],
      positions: t.positionAssignments.map((pa: PositionAssignment) => pa.positionName),
    };
  }

  // Legacy migration: create positionAssignments from old positions[] array
  const assignments: PositionAssignment[] = (t.positions || []).map((posName: string, idx: number) => ({
    id: `${t.id}_PA${idx}`,
    positionName: posName,
    category: 'Individual Lesson',  // Safe default
    rateType: 'HOURLY' as const,
    rateValue: 0,                   // Unknown until user sets it
  }));

  return {
    ...t,
    tags: t.tags || [],
    positionAssignments: assignments,
    positions: t.positions || [],
  };
};

export const INITIAL_SETTINGS: AppSettings = {
  language: 'en-US',
  dateFormat: 'DD/MM/YYYY',
  timeFormat: '12h',
  timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  defaultEventDuration: 60,
  weekNumberDisplay: 'none',
  currency: '₪',
  developerMode: false
};

export const INITIAL_LISTS: ListsState = {
  positions: ['Piano Instructor', 'Voice Coach', 'Violin Teacher', 'Choir Director', 'Theory Teacher'],
  tags: ['Piano Dept', 'Strings Dept', 'Vocal Dept', 'Senior Staff', 'Junior Staff'],
  classifications: Object.values(Classification) as string[]
};

export const HEBREW_CALENDAR_OPTIONS = {
  // Config for Hebcal if needed
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    'app.title': 'Music Center Calendar',
    'app.subtitle': 'Management System',
    'nav.calendar': 'Smart Calendar',
    'nav.gantt': 'Gantt & Blackout',
    'nav.teachers': 'Teachers',
    'nav.rooms': 'Rooms',
    'nav.lists': 'Manage Lists',
    'nav.manage': 'Manage',
    'nav.financial': 'Financial Dashboard',
    'nav.settings': 'Settings',
    'nav.power_tools': 'Power Tools',
    'nav.analysis': 'Financial Analysis',
    'nav.super_admin': 'Super Admin',
    'nav.mobile_access': 'Mobile Access',
    'ops': 'Operations',
    'admin': 'Administration',
    'analytics': 'Analytics',
    'today': 'TODAY',
    // Buttons
    'btn.add': 'Add',
    'btn.create': 'Create',
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.delete': 'Delete',
    'btn.close': 'Close',
    'btn.confirm': 'Confirm',
    'btn.back': 'Back',
    'btn.export': 'Export',
    'btn.import': 'Import',
    'btn.clear_all': 'Clear All',
    'btn.sign_out': 'Sign Out',
    'btn.connect_account': 'Connect My Account',
    'btn.disconnect': 'Disconnect',
    'btn.reconnect': 'Reconnect',
    'btn.save_insight': 'Save Insight',
    'btn.download_report': 'Download Report (CSV)',
    // Calendar view
    'mode.day': 'DAY',
    'mode.week': 'WEEK',
    'mode.month': 'MONTH',
    'mode.list': 'LIST',
    'filter.teacher': 'Teacher: All',
    'filter.room': 'Room: All',
    'filter.type': 'Type: All',
    'filter.category_all': 'Category: All',
    'filter.no_filters': 'No Filters',
    'filter.show_canceled': 'Show Canceled',
    'filter.show_blackouts': 'Show Blackouts',
    'filter.all_teachers': 'All Teachers',
    'filter.all_categories': 'All Categories',
    'filter.all_types': 'All Types',
    'filter.all_tags': 'All Tags',
    'filter.by_position': 'Filter by Position',
    'filter.by_tag': 'Filter by Tag',
    // Event modal
    'modal.add_event': 'Add Event',
    'modal.edit_event': 'Edit Event',
    'label.name': 'Event Name',
    'label.desc': 'Description',
    'label.teacher': 'Teacher',
    'label.room': 'Room',
    'label.type': 'Type',
    'label.start': 'Start',
    'label.end': 'End',
    'label.date': 'Date',
    'label.position': 'Position',
    'label.recurrence': 'Recurrence',
    'label.full_name': 'Full Name',
    'label.teacher_color': 'Teacher Color',
    'label.category': 'Category',
    'label.rate_type': 'Rate Type',
    'label.room_name': 'Room Name',
    'label.itinerary_desc': 'Itinerary / Description',
    'label.from': 'From',
    'label.to': 'To',
    'label.optional': '(Optional)',
    'label.requires_teacher': '(Requires Teacher & Position)',
    'label.live': 'Live',
    'label.no_room': 'No Room',
    'label.no_room_dash': '— No Room —',
    // Calendar states
    'cal.canceled': 'CANCELED',
    'cal.no_events': 'No events',
    'cal.hide_canceled': 'Hide Canceled',
    'cal.hide_blackouts': 'Hide Blackouts',
    'cal.recurring_event': 'Recurring Event',
    'cal.every': 'Every',
    'cal.on_days': 'On days',
    'cal.monthly_mode': 'Monthly mode',
    'cal.mark_canceled': 'Mark as Canceled',
    'cal.cancel_pay_status': 'Cancellation Pay Status',
    'cal.no_pay': 'No Pay',
    'cal.paid_cancel': 'Paid Cancellation',
    'cal.delete_event': 'Delete Event',
    'cal.payment_method': 'Payment Method',
    'cal.select_category': 'Select Category',
    'cal.save_changes': 'Save Changes',
    'cal.save_update_series': 'Save & Update Series',
    'cal.update_this_only': 'Update This Only',
    'cal.update_all_future': 'Update All Future',
    'cal.recurring_series_msg': 'This is part of a recurring series. What would you like to',
    'cal.this_event_only': 'This event only',
    'cal.this_and_future': 'This and all future events',
    'cal.all_in_series': 'All events in series',
    // Calendar recurrence
    'recurrence.none': 'Does not repeat',
    'recurrence.daily': 'Daily',
    'recurrence.weekly': 'Weekly',
    'recurrence.biweekly': 'Bi-Weekly',
    'recurrence.monthly': 'Monthly',
    'recurrence.yearly': 'Yearly',
    'recurrence.until': 'Until',
    'recurrence.ends_after': 'Ends after',
    'recurrence.ends_on': 'Ends on',
    'recurrence.occurrences': 'occurrences',
    // Settings
    'settings.general': 'General Settings',
    'settings.integrations': 'Integrations',
    'settings.dev_tools': 'Developer Tools',
    'settings.generate_data': 'Generate Test Data',
    'settings.generate_data_desc': 'Populate the calendar with 20 teachers and random events.',
    'settings.generate_btn': 'Generate Data',
    'settings.unsaved': 'You have unsaved changes',
    'settings.testing_tools': 'Testing Tools',
    'settings.currency': 'Currency',
    'settings.currency_symbol': 'Currency Symbol',
    'settings.currency_desc': 'This symbol will appear next to all cost values in the financial dashboard, analysis, and exports.',
    'settings.gcal_sync': 'Google Calendar Sync',
    'settings.gcal_desc': 'Push scheduled lessons to the tenant admin\'s Google Calendar.',
    'settings.connected_via': 'Connected via',
    'settings.sync_inactive': 'Different account — sync inactive for you',
    'settings.token_expired': 'Authentication token expired. Please reconnect to restore sync.',
    'settings.fetching_cals': 'Fetching your calendars...',
    'settings.select_calendar': 'Select Target Calendar',
    'settings.choose_cal': '-- Choose a calendar --',
    'settings.primary': '(Primary)',
    'settings.auto_add_desc': 'New lessons will be automatically added to this calendar.',
    'settings.sync_managed_by': 'Calendar sync is managed by {email}',
    'settings.sync_condition': 'Events will only sync to Google Calendar when the designated admin ({email}) is logged in.',
    'settings.admin_only': 'Admin only',
    'settings.managed_by_admin': 'Managed by tenant admin',
    'settings.week_hidden': 'Hidden',
    'settings.week_number': 'Week Number',
    'settings.week_of': 'Week of...',
    // Labels
    'label.default_lang': 'Default Language',
    'label.system_default': 'System Default',
    'label.coming_soon': 'Coming Soon',
    'label.timezone': 'Time Zone',
    'label.date_format': 'Date Format',
    'label.time_format': 'Time Format',
    'label.calendar_defaults': 'Calendar Defaults',
    'label.default_duration': 'Default Event Duration (minutes)',
    'label.week_numbers': 'Week Number Display',
    'label.blackout': 'BLACKOUT',
    // Nav sections
    'nav.section.localization': 'Localization',
    'nav.section.date_time': 'Date & Time',
    'nav.section.analytics': 'Analytics',
    'nav.section.operations': 'Operations',
    'nav.section.admin': 'Administration',
    // Roles
    'role.admin': 'Admin',
    'role.viewer': 'Viewer',
    // Alerts
    'alert.confirm_generate': 'This will overwrite existing teachers and events. Continue?',
    'alert.data_generated': 'Test data generated!',
    'alert.delete_event': 'Are you sure you want to delete this event?',
    'alert.delete_gantt': 'Delete this Gantt block? This may affect blackouts.',
    'alert.end_time_error': 'End time must be after start time',
    'alert.delete_teacher': 'Are you sure you want to delete this teacher? Associated events will show warnings.',
    'alert.delete_room': 'Are you sure? Scheduled events will flag warnings.',
    'alert.delete_gantt_block': 'Delete this block? If it is a blackout, events will be restored.',
    'alert.error_reading_file': 'Error reading file',
    'alert.no_valid_teachers': 'No valid or new unique teachers found in CSV.',
    'alert.no_valid_rows': 'No valid rows found. Please ensure dates are in YYYY-MM-DD or DD/MM/YYYY format.',
    'alert.csv_parse_fail': 'Failed to parse CSV file.',
    'alert.delete_all_data': 'Are you sure you want to permanently delete all Teachers, Rooms, Events, and Gantt Blocks from THIS workspace in the cloud?',
    'alert.action_cannot_undo': 'This action cannot be undone.',
    // Power Tools
    'pt.bulk_delete': 'Bulk Delete',
    'pt.date_range': 'Date Range',
    'pt.criteria': 'Filter Criteria',
    'pt.preview': 'Preview',
    'pt.delete_all': 'Delete All Matches',
    'pt.confirm_delete': 'Please confirm deletion of {count} events.',
    'pt.success': 'Successfully deleted {count} events.',
    'pt.no_matches': 'No matching events found.',
    'pt.time_range': 'Time Range',
    'pt.interactive': 'Interactive Selection',
    'pt.import_csv': 'Import Schedule from CSV',
    // Financial Dashboard
    'fin.title': 'Financial Dashboard',
    'fin.all_time': 'All Time',
    'fin.grand_total': 'Grand Total',
    'fin.hourly_fees': 'Hourly Fees',
    'fin.global_monthly': 'Global Monthly',
    'fin.active_hours': 'Active Hours',
    'fin.canceled': 'Canceled',
    'fin.teacher_metrics': 'Teacher Metrics',
    'fin.sort_hint': '· Click headers to sort',
    'fin.current_week': 'Current Week',
    'fin.daily': 'Daily',
    'fin.hourly': 'Hourly',
    'fin.weekly': 'Weekly',
    'fin.monthly': 'Monthly',
    'fin.revenue_trend': 'Revenue Trend',
    // Table headers
    'col.name': 'Name',
    'col.active_hrs': 'Active Hrs',
    'col.canceled_hrs': 'Canceled Hrs',
    'col.cancel_count': 'Cancel #',
    'col.hourly_cost': 'Hourly Cost',
    'col.one_off_cost': 'One-Off Cost',
    'col.global_cost': 'Global Cost',
    'col.total': 'Total',
    'col.recipient': 'Recipient',
    'col.email_address': 'Email Address',
    'col.total_payout': 'Total Payout',
    'col.positions_rates': 'Positions & Rates',
    'col.contact': 'Contact',
    'col.rates': 'Rates',
    'col.entry_name': 'Entry Name',
    'col.actions': 'Actions',
    // Financial Analysis
    'fin_ana.title': 'Financial Analysis',
    'fin_ana.delete_chart': 'Delete Chart',
    'fin_ana.insight_title': 'Insight Title',
    'fin_ana.metric': 'Metric',
    'fin_ana.total_active_hours': 'Total Active Hours',
    'fin_ana.total_canceled_hours': 'Total Canceled Hours',
    'fin_ana.hourly_payroll': 'Hourly Payroll',
    'fin_ana.global_payroll': 'Global Payroll',
    'fin_ana.grand_total_payroll': 'Grand Total Payroll',
    'fin_ana.avg_hours_teacher': 'Avg Hours per Teacher',
    'fin_ana.avg_payroll_teacher': 'Avg Payroll per Teacher',
    'fin_ana.cancel_rate': 'Cancellation Rate',
    'fin_ana.highest_earner': 'Highest Earner',
    'fin_ana.lowest_earner': 'Lowest Earner',
    'fin_ana.choose_insights': 'Choose Visible Insights',
    'fin_ana.no_insights': 'No insights selected. Click Edit to choose which insights to display.',
    'fin_ana.create_first_chart': 'Create your first custom chart',
    'fin_ana.back_to_dashboard': 'Back to Dashboard',
    'fin_ana.classify_desc': 'Classify data by category (timeframes are controlled separately below)',
    'fin_ana.select_period_desc': 'Select the time period for analysis (independent of grouping)',
    // Teacher Manager
    'teach.title': 'Teacher Management',
    'teach.add': 'Add Teacher',
    'teach.import_title': 'Import Teachers',
    'teach.import_csv': 'Import Teachers from CSV',
    'teach.csv_columns': 'Select your .csv file with columns: Name, Email, Phone, Tags',
    'teach.colors_auto': '* Colors will be auto-assigned',
    'teach.add_first_position': '+ Add first position',
    'teach.position_assignment': 'Position Assignment',
    'teach.select_to_import': 'Select Teachers to Import',
    'teach.unique_teachers': 'unique teachers. Select the ones you want to import.',
    'teach.selected': 'Selected',
    'teach.already_in_list': 'Already in list',
    'teach.skip': 'Skip',
    'teach.no_teachers_found': 'No teachers found in this file.',
    'teach.back_to_list': 'Back to List',
    // Room Manager
    'room.title': 'Room Management',
    'room.itinerary': 'Itinerary & Equipment',
    // Gantt
    'gantt.title': 'Semesters & Blackouts',
    'gantt.subtitle': 'Manage semesters & blackouts.',
    'gantt.label_title': 'Title',
    'gantt.start_date': 'Start Date',
    'gantt.end_date': 'End Date',
    'gantt.display_color': 'Display Color',
    'gantt.apply_blackout': 'Apply Blackout',
    'gantt.blackout_desc': 'Automatically HIDE all events in this range from calendar and reports.',
    // Chart Builder
    'chart.title_label': 'Chart Title',
    'chart.filter_mode': 'Filter Mode',
    'chart.live': 'Live',
    'chart.live_desc': 'Reacts to dashboard filters',
    'chart.snapshot': 'Snapshot',
    'chart.snapshot_desc': 'Freezes filters at save time',
    'chart.sort_by': 'Sort By',
    'chart.dimension_label': 'Dimension Label',
    'chart.ascending': 'Ascending',
    'chart.descending': 'Descending',
    'chart.no_options': 'No options available',
    'chart.add_position': 'Add Position',
    'chart.position_name': 'Position Name',
    'chart.select_icon': 'Select Icon',
    'chart.choose_icon': 'Choose an icon for this position',
    // Filter sections
    'filter.teachers': 'Teachers',
    'filter.positions': 'Positions',
    'filter.tags': 'Tags',
    'filter.categories': 'Categories',
    'filter.rate_type': 'Rate Type',
    // Manage Lists
    'lists.title': 'Dropdown Lists',
    'lists.desc': 'Update your app by modifying these lists.',
    'lists.classifications': 'Classifications',
    'lists.how_to': 'How to use this tool:',
    'lists.step1': '1. Fill in the data below',
    'lists.step2': '2. Export to CSV',
    'lists.step3': '3. Open in your app',
    'lists.add_row': 'Add Row',
    'lists.template': 'Template',
    // Auth
    'auth.sign_in_google': 'Sign In with Google',
    'auth.workspaces': 'Authorized Workspaces',
    'auth.no_workspaces': 'No authorized workspaces found.',
    'auth.signing_in': 'Syncing with Cadenza Cloud...',
    // Tooltips
    'tooltip.edit': 'Edit',
    'tooltip.duplicate': 'Duplicate',
    'tooltip.delete': 'Delete',
    'tooltip.switch_light': 'Switch to Light Mode',
    'tooltip.switch_dark': 'Switch to Dark Mode',
    'tooltip.expand_sidebar': 'Expand Sidebar',
    'tooltip.collapse_sidebar': 'Collapse Sidebar',
    'tooltip.open_menu': 'Open Menu',
    'tooltip.add_event': 'Click to add event',
    'tooltip.toggle_filters': 'Toggle Filters',
    'tooltip.remove_position': 'Remove position',
    // Placeholders
    'placeholder.search_teachers': 'Search teachers...',
    'placeholder.or_type_new': 'Or type new...',
    'placeholder.event_name': 'e.g. Piano Lesson',
    'placeholder.room_details': 'Details about equipment, capacity, etc.',
    'placeholder.choose_calendar': '-- Choose a calendar --',
    // Dynamic
    'dynamic.rate_hourly': 'Rate ({currency}/hour)',
    'dynamic.monthly_fee': 'Monthly Fee ({currency})',
    'dynamic.send_reports': 'Send {n} Reports',
    'dynamic.week_of': 'Week of {date}',
    'dynamic.hourly_currency': 'Hourly ({currency})',
    'dynamic.one_off_currency': 'One-Off ({currency})',
    'dynamic.global_currency': 'Global ({currency})',
    'dynamic.total_currency': 'Total ({currency})',
    'dynamic.one_off_price': 'One-Off Price ({currency})',
    // Footer
    'footer.copyright': '© 2026 Music Center',
    // Super Admin
    'super.title': 'Super Admin',
    'super.delete_all': 'Delete All Data',
    'analysis.title': 'Financial Analysis',
    'analysis.subtitle': 'Insights, charts, comparisons, and deep data exploration.',
    'analysis.key_insights': 'Key Insights',
    'analysis.charts': 'Charts',
    'analysis.new_chart': 'New Chart',
    'analysis.create_first_chart': 'Create your first custom chart',
    'analysis.create_first_chart_desc': 'Group data by any dimension, pick metrics, and choose a visualization',
    'analysis.advanced_filters': 'Advanced Filters',
    'analysis.clear_all': 'Clear all',
    'analysis.choose_insights': 'Choose Visible Insights',
    'analysis.custom_insight': 'Custom Insight',
    'analysis.show_all': 'Show All',
    'analysis.no_insights': 'No insights selected.',
    'analysis.click_edit': 'Click Edit to choose which insights to display.',
    'analysis.filters': 'Filters',
    'analysis.back_to_dashboard': 'Back to Dashboard',
    'analysis.open_menu': 'Open Menu',
    'time.current_week': 'Current Week',
    'time.current_month': 'Current Month',
    'time.custom_range': 'Custom Range',
    'time.all_time': 'All Time',
    'time.today': 'Today',
    'time.specific_day': 'Specific Day',
    'time.specific_week': 'Specific Week',
    'time.specific_month': 'Specific Month',
    'insight.most_hours': 'Most Hours Taught',
    'insight.most_canceled': 'Most Canceled Hours',
    'insight.highest_payroll': 'Highest Payroll',
    'insight.lowest_payroll': 'Lowest Payroll',
    'insight.cancel_rate': 'Cancellation Rate',
    'insight.avg_cost': 'Avg Cost / Teacher',
    'insight.top_position': 'Top Position (Hrs)',
    'insight.cost_split': 'Hourly vs Global',
    'insight.most_positions': 'Most Positions',
    'insight.active_teachers': 'Active Teachers',
    'insight.of_active_hours': 'of all active hours',
    'insight.of_their_hours': 'of their total hours',
    'insight.no_cancellations': 'No cancellations',
    'insight.of_total_payroll': 'of total payroll',
    'insight.of_total': 'of total',
    'insight.no_data': 'No data',
    'insight.most_active_position': 'Most active position',
    'metric.total_active_hours': 'Total Active Hours',
    'metric.total_canceled_hours': 'Total Canceled Hours',
    'metric.hourly_payroll': 'Hourly Payroll',
    'metric.oneoff_payroll': 'One-Off Payroll',
    'metric.global_payroll': 'Global Payroll',
    'metric.grand_total': 'Grand Total Payroll',
    'metric.avg_hours': 'Avg Hours per Teacher',
    'metric.avg_payroll': 'Avg Payroll per Teacher',
    'metric.highest_earner': 'Highest Earner',
    'metric.lowest_earner': 'Lowest Earner',
    'metric.all_teachers': 'All Teachers',
    'modal.new_insight': 'New Insight',
    'modal.insight_title': 'Insight Title',
    'modal.metric': 'Metric',
    'modal.filter_by_teacher': 'Filter by Teacher (Optional)',
    'modal.save_insight': 'Save Insight',
    'modal.totals': 'Totals',
    'modal.averages_rates': 'Averages & Rates',
    'modal.extremes': 'Extremes',
    'modal.delete_chart': 'Delete Chart',
    'modal.cannot_undo': 'This action cannot be undone.',
    'modal.confirm_delete_chart': 'Are you sure you want to delete',
    'chart.updated': 'Updated',
    'chart.edit': 'Edit',
    'chart.duplicate': 'Duplicate',
    'chart.delete': 'Delete',
    'chart.done': 'Done',
    'filter.hourly': 'Hourly',
    'filter.global_monthly': 'Global Monthly',
    'builder.title': 'Chart Builder',
    'builder.edit_chart': 'Edit Chart',
    'builder.chart_title': 'Chart Title',
    'builder.dimension_label': 'Dimension Label',
    'builder.preview': 'Preview',
    'builder.save_chart': 'Save Chart',
    'cal.teacher': 'Teacher',
    'cal.room': 'Room',
    'cal.description': 'Description',
    'cal.event_name': 'Event Name',
    'cal.type': 'Type',
    'cal.start': 'Start',
    'cal.end': 'End',
    'cal.add_event': 'Add Event',
    'cal.edit_event': 'Edit Event',
    'cal.recurrence': 'Recurrence',
    'cal.no_repeat': 'Does not repeat',
    'cal.daily': 'Daily',
    'cal.weekly': 'Weekly',
    'cal.monthly': 'Monthly',
    'cal.yearly': 'Yearly',
    'lists.manage_title': 'Manage Lists',
    'lists.configure_desc': 'Configure global dropdown options for Positions, Tags, and Classifications.',
    'lists.positions': 'Positions',
    'lists.tags': 'Tags',
    'lists.import_preview': 'Import Preview',
    'lists.new_positions': 'New Positions',
    'lists.new_tags': 'New Tags',
    'lists.new_classifications': 'New Classifications',
    'lists.import_all': 'Import All',
    'lists.no_items': 'No items found',
    'lists.import_csv': 'Import CSV',
    'room.add': 'Add Room',
    'room.edit': 'Edit Room',
    'room.add_new': 'Add New Room',
    'room.itinerary_desc': 'Itinerary / Description',
    'room.no_rooms': 'No rooms configured. Add one to get started.',
    'room.no_details': 'No details provided.',
    'room.equipment': 'Equipment',
    'cal.today': 'TODAY',
    'cal.day': 'DAY',
    'cal.week': 'WEEK',
    'cal.month': 'MONTH',
    'cal.toggle_filters': 'Toggle Filters',
    'cal.week_of': 'Week of',
    'cal.week_num': 'Week',
    'cal.click_add': 'Click to add event',
    'cal.unnamed': 'Unnamed Event',
    'cal.blackout_period': 'BLACKOUT PERIOD',
    'cal.recurring': 'Recurring',
    'cal.part_of_series': 'Part of Series',
    'cal.filter.teacher_all': 'Teacher: All',
    'cal.filter.room_all': 'Room: All',
    'cal.filter.type_all': 'Type: All',
    'cal.filter.position_all': 'Position: All',
    'cal.filter.tag_all': 'Tag: All',
    'cal.detail.edit': 'Edit',
    'cal.detail.restore': 'Restore',
    'cal.detail.cancel_event': 'Cancel',
    'cal.detail.delete': 'Delete',
    'speed.power_tools': 'Power Tools',
    'speed.gantt_view': 'Gantt View',
    'speed.new_event': 'New Event',
    'event.new': 'New Event',
    'event.edit': 'Edit Event',
    'event.name': 'Event Name',
    'event.name_placeholder': 'e.g. Piano Lesson',
    'event.category': 'Category',
    'event.select_category': 'Select Category',
    'event.teacher_lessons': 'Teacher Lessons',
    'event.individual_lesson': 'Individual Lesson',
    'event.group_lesson': 'Group Lesson',
    'event.general_events': 'General Events',
    'event.teacher': 'Teacher',
    'event.optional': '(Optional)',
    'event.select_teacher': 'Select Teacher',
    'event.org_no_teacher': 'Organization / No Teacher (Optional)',
    'event.select_category_first': 'Select Category First',
    'event.position': 'Position',
    'event.select_teacher_first': 'Select Teacher First',
    'event.no_positions': 'No positions available for this teacher under this category',
    'event.select_position': 'Select a position',
    'event.payment_method': 'Payment Method',
    'event.no_payment': 'No Payment (Scheduling Only)',
    'event.use_position_rate': 'Use Position Rate',
    'event.requires_teacher_position': '(Requires Teacher & Position)',
    'event.one_off_payment': 'One-Off Payment',
    'event.one_off_price': 'One-Off Price',
    'event.room': 'Room',
    'event.no_room': 'No Room',
    'event.start_time': 'Start Time',
    'event.end_time': 'End Time',
    'event.description_label': 'Description',
    'recurrence.recurring_event': 'Recurring Event',
    'recurrence.every': 'Every',
    'recurrence.days': 'day(s)',
    'recurrence.weeks': 'week(s)',
    'recurrence.months': 'month(s)',
    'recurrence.on_days': 'On days',
    'recurrence.monthly_mode': 'Monthly mode',
    'recurrence.on_day_n': 'On day',
    'recurrence.ends': 'Ends',
    'recurrence.never': 'Never',
    'recurrence.after_n': 'After N occurrences',
    'recurrence.on_date': 'On date',
    'settings.managed_by_tenant': 'Managed by tenant admin',
    'settings.hidden': 'Hidden',
    'settings.mobile_access': 'Mobile Access',
    'power.all_teachers': 'All Teachers',
    'power.all_types': 'All Types',
    'power.all_tags': 'All Tags',
    'teacher.all_categories': 'All Categories',
    'teacher.filter_position': 'Filter by Position',
    'teacher.filter_tag': 'Filter by Tag',
    'teacher.remove_position': 'Remove position',
    'teacher.select_from_list': 'Select from list...',
    'gantt.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.not_found': 'Not found',
    'common.sandbox': 'SANDBOX',
    'builder.group_by': 'Group By',
    'builder.group_by_desc': 'Classify data by category (timeframes are controlled separately below)',
    'builder.metrics': 'Metrics',
    'builder.add': 'Add',
    'builder.by': 'by',
    'builder.timeframe': 'Timeframe',
    'builder.timeframe_desc': 'Select the time period for analysis (independent of grouping)',
    'builder.events_in_timeframe': 'events in selected timeframe',
    'builder.comparison_mode': 'Comparison Mode',
    'builder.comparison_active': 'Comparison Mode is active — add periods to compare against the primary timeframe',
    'builder.comparison_inactive': 'Compare the same filters against different periods of the same timeframe type',
    'builder.side_by_side': 'Side by Side',
    'builder.merged': 'Merged',
    'builder.comparison_n': 'Comparison',
    'builder.select_comparison_day': 'Select comparison day:',
    'builder.pick_date_in_week': 'Pick a date within the comparison week:',
    'builder.select_comparison_month': 'Select comparison month:',
    'builder.select_comparison_range': 'Select comparison date range:',
    'builder.to': 'to',
    'builder.events': 'events',
    'builder.add_another': 'Add Another Comparison',
    'builder.visualization': 'Visualization',
    'builder.metrics_displayed': 'metrics — displayed as',
    'builder.stacked_segments': 'stacked segments',
    'builder.grouped_series': 'grouped series',
    'builder.data_filters': 'Data Filters',
    'builder.filter_desc': 'Narrow chart data by specific teachers, positions, tags, or categories',
    'builder.clear_all_filters': 'Clear all filters',
    'builder.filter_mode': 'Filter Mode',
    'builder.live': 'Live',
    'builder.live_desc': 'Reacts to dashboard filters',
    'builder.snapshot': 'Snapshot',
    'builder.snapshot_desc': 'Freezes filters at save time',
    'builder.active': 'Active:',
    'builder.advanced': 'Advanced Options',
    'builder.sort_by': 'Sort By',
    'builder.ascending': 'Ascending',
    'builder.descending': 'Descending',
    'builder.limit_topn': 'Limit (Top N)',
    'builder.no_limit': '0 = no limit',
    'builder.show_all': '0 = show all groups',
    'builder.live_preview': 'Live Preview',
    'builder.merged_overlay': 'MERGED OVERLAY',
    'builder.side_by_side_label': 'SIDE BY SIDE',
    'builder.cancel': 'Cancel',
    'builder.update_chart': 'Update Chart',
    'builder.create_chart': 'Create Custom Chart',
    'builder.chart_title_placeholder': 'e.g., Monthly Cost Trend, Hours by Department...',
    'builder.pick_date_desired_week': 'Pick any date within the desired week:',
    'builder.primary': 'Primary',
    'builder.select_period': 'Select a period',
    'builder.custom_range': 'Custom Range',
    'builder.week_of': 'Week of',
    'viz.bar': 'Bar',
    'viz.stacked': 'Stacked',
    'viz.line': 'Line',
    'viz.pie': 'Pie',
    'viz.table': 'Table',
    'agg.sum': 'Sum',
    'agg.average': 'Average',
    'agg.count': 'Count',
    'agg.min': 'Min',
    'agg.max': 'Max',
    'tf.today': 'Today',
    'tf.current_week': 'Current Week',
    'tf.current_month': 'Current Month',
    'tf.custom_range': 'Custom Range',
    'tf.specific_day': 'Specific Day',
    'tf.specific_week': 'Specific Week',
    'tf.specific_month': 'Specific Month',
    'dropdown.all': 'All',
    'dropdown.selected': 'selected',
    'dropdown.select_all': 'Select All',
    'dropdown.clear': 'Clear',
    'dropdown.no_options': 'No options available',
    'filter.rate_types': 'Rate Types',
    'builder.teacher_s': 'teacher(s)',
    'builder.position_s': 'position(s)',
    'builder.tag_s': 'tag(s)',
    'builder.category_ies': 'categor(ies)',
    'builder.rate_type_s': 'rate type(s)',
    'builder.metric': 'metric',
    'builder.metrics_word': 'metrics',
    'builder.filter': 'filter',
    'builder.filters_word': 'filters',
    'builder.applied': 'applied',
    'cal.aria_toggle_canceled': 'Toggle canceled events visibility',
    'cal.aria_toggle_blackouts': 'Toggle blackout events visibility',
    'settings.open_menu': 'Open Menu',
    'common.sign_out': 'Sign Out',
    'room.details_placeholder': 'Details about equipment, capacity, etc.',
    'teacher.or_type_new': 'Or type new...',
    'financial.delete_title': 'Delete',
    'teach.col_name': 'Name',
    'teach.col_positions': 'Positions & Rates',
    'teach.col_tags': 'Tags',
    'teach.col_contact': 'Contact',
    'teach.col_actions': 'Actions',
    'teach.template': 'Template',
    'teach.export': 'Export',
    'teach.import': 'Import',
    'teach.subtitle': 'Manage instructor profiles, positions, rates, and tags.',
    'teach.select_position_placeholder': 'Select Position...',
    'teach.select_tag_placeholder': 'Select Tag...',
    'teach.edit_teacher': 'Edit Teacher',
    'teach.add_new_teacher': 'Add New Teacher',
    'teach.position_assignments_label': 'Position Assignments',
    'teach.add_position': 'Add Position',
    'teach.position_name': 'Position Name',
    'teach.category': 'Category',
    'teach.rate_type': 'Rate Type',
    'teach.hourly': 'Hourly',
    'teach.global_monthly': 'Global Monthly',
    'teach.rate_hourly_label': 'Rate',
    'teach.per_hour': '/hour',
    'teach.monthly_fee': 'Monthly Fee',
    'teach.no_positions_yet': 'No positions assigned yet.',
    'teach.position_placeholder': 'e.g. Piano Instructor',
    'teach.tags_label': 'Tags',
    'teach.add_tag': 'Add',
    'teach.email': 'Email',
    'teach.phone': 'Phone',
    'teach.cancel': 'Cancel',
    'teach.save': 'Save',
    'teach.import_teachers': 'Import Teachers',
    'teach.import_col_name': 'Name',
    'teach.import_col_email': 'Email',
    'teach.import_col_positions': 'Positions',
    'teach.import_col_rates': 'Rates',
    'teach.import_n_teachers': 'Import',
    'teach.teachers_word': 'Teachers',
    'teach.delete_selection': 'Delete Selection',
    'sa.access_denied': 'Access Denied',
    'sa.restricted': 'This area is restricted to the platform super-administrator.',
    'sa.console_title': 'Super Admin Console',
    'sa.console_subtitle': 'Manage Tenants, Access Control & Developer Tools',
    'sa.tab_orgs': 'Organizations',
    'sa.tab_access': 'Access Mappings',
    'sa.tab_dev': 'Developer Tools',
    'sa.register_org': 'Register New Organization',
    'sa.org_name': 'Organization Name',
    'sa.org_name_placeholder': 'e.g. Alpert Music Center',
    'sa.url_slug': 'URL Slug (ID)',
    'sa.url_slug_placeholder': 'e.g. alpert (no spaces)',
    'sa.id_label': 'ID:',
    'sa.edit_org_title': 'Edit Organization',
    'sa.upload_logo': 'Upload Logo',
    'sa.delete_org': 'Delete Organization',
    'sa.save_changes': 'Save Changes',
    'sa.cancel': 'Cancel',
    'sa.no_orgs': 'No organizations registered yet.',
    'sa.map_user': 'Map User to Organization',
    'sa.user_email': 'User Email (Gmail)',
    'sa.user_email_placeholder': 'user@gmail.com',
    'sa.organization': 'Organization',
    'sa.select_org': 'Select Org...',
    'sa.all_orgs': 'All Organizations',
    'sa.viewer': 'VIEWER',
    'sa.admin': 'ADMIN',
    'sa.revoke_access': 'Revoke Access',
    'sa.generate_test': 'Generate Test Data',
    'sa.state_snapshot': 'State Snapshot',
    'sa.snapshot_desc': 'Save current app data to browser storage or restore from a previous snapshot.',
    'sa.create_snapshot': 'Create Snapshot',
    'sa.snapshot_created': 'Snapshot created successfully!',
    'sa.snapshot_created_short': 'Snapshot created!',
    'sa.test_generated': 'Test data generated successfully!',
    'sa.no_snapshot': 'No snapshot found.',
    'sa.testing_tools': 'Testing Tools',
    'sa.testing_desc': 'Actions specific for evaluating Layer 1 logic.',
    'sa.run_calendar_test': 'Run Calendar Test Gen',
    'sa.run_teacher_gen': 'Run Teacher Gen',
    'sa.system_info': 'System Information',
    'sa.super_admin_label': 'Super Admin',
    'sa.total_tenants': 'Total Tenants',
    'sa.total_access': 'Total Access Records',
    'sa.superadmin_badge': 'SUPERADMIN',
    'settings.english_us': 'English (United States)',
    'settings.tz_utc': 'UTC',
    'settings.tz_jerusalem': 'Jerusalem (Israel)',
    'settings.tz_eastern': 'Eastern Time (US & Canada)',
    'settings.tz_pacific': 'Pacific Time (US & Canada)',
    'settings.date_mmddyyyy': 'MM/DD/YYYY (04/16/2026)',
    'settings.date_ddmmyyyy': 'DD/MM/YYYY (16/04/2026)',
    'settings.date_iso': 'YYYY-MM-DD (2026-04-16)',
    'settings.gcal_label': 'GCal',
    'settings.gcal_title': 'Google Calendar Sync',
    'settings.gcal_reconnect': 'Reconnect',
    'settings.gcal_auto_note': 'New lessons will be automatically added to this calendar.',
    'power.time_range': 'Time Range',
    'power.criteria': 'Criteria',
    'power.interactive_selection': 'Interactive Selection',
    'power.selected_events': 'Selected Events:',
    'power.import_csv_title': 'Import Schedule from CSV',
    'power.import_csv_desc': 'Bulk import semesters, holidays, or blackout periods.',
    'power.blackout_label': 'BLACKOUT',
    'power.alert_deleted': 'Successfully deleted ${count} events.',
    'power.alert_no_valid': 'No valid rows found. Please ensure dates are in YYYY-MM-DD or M/D/YYYY format.',
    'power.alert_parse_fail': 'Failed to parse CSV file.',
    'power.alert_imported': 'Successfully imported ${n} schedule blocks.',
    'layout.logo_alt': 'Cadenza Logo',
    'layout.sandbox_badge': 'SANDBOX',
    'layout.sign_out': 'Sign Out',
    'layout.mobile_access_label': 'Mobile Access',
    'analysis.chart_name_placeholder': 'e.g. Piano Revenue',
    'analysis.edit_tooltip': 'Edit',
    'analysis.duplicate_tooltip': 'Duplicate',
    'gantt.name_placeholder': 'e.g. Winter Break',
    'gantt.auto_hide': 'Automatically',
    'gantt.hide_label': 'HIDE',
    'dashboard.report_desc': 'Based on current filters, reports will be sent to the following teachers.',
    'dashboard.report_success': 'Reports Sent Successfully!',
    'lists.no_items_found': 'No items found',
    'lists.csv_no_unique': 'No new unique items found in the CSV. Make sure you used the template format.',
    'room.subtitle': 'Configure spaces and equipment itineraries.',
    'room.name_placeholder': 'e.g. Studio A',
    'teach.alert_error_reading': 'Error reading file',
    'teach.alert_no_valid': 'No valid or new unique teachers found in CSV.\nPlease ensure the file contains columns: Name, Email, Phone, Position, Category, RateType, RateValue, Tags',
    'cal.alert_end_after_start': 'End time must be after start time',
    'power.title': 'Power Tools',
    'power.subtitle': 'Bulk actions for event management.',
    'power.tab_filter': 'By Filter',
    'power.tab_manual': 'Manual Select',
    'power.tab_import': 'Import Schedule',
    'power.label_from': 'From',
    'power.label_to': 'To',
    'power.select_time_range_first': 'Please select a time range first.',
    'power.clear_filters': 'Clear Filters',
    'power.manual_desc': 'Click and drag directly on the calendar grid to draw a selection rectangle, or click individual events to toggle them.',
    'power.clear_selection': 'Clear Selection',
    'power.download_template': 'Download CSV Template',
    'power.processing': 'Processing...',
    'power.drop_csv': 'Drop CSV file or Click to Browse',
    'power.preview': 'Preview',
    'power.items': 'items',
    'power.confirm_import': 'Confirm Import',
    'power.targeted': 'targeted',
    'power.adjust_filters': 'Adjust filters.',
    'power.select_events': 'Select events.',
    'power.bulk_cancel': 'Bulk Cancel',
    'power.bulk_delete': 'Bulk Delete',
    'power.confirm_action': 'Are you sure you want to',
    'power.action_cancel': 'CANCEL',
    'power.action_delete': 'PERMANENTLY DELETE',
    'power.events_word': 'events',
    'power.matching': 'matching',
    'power.selected_word': 'selected',
    'power.alert_canceled': 'Successfully canceled',
    'power.alert_cancel_note': 'Note: Canceled events may be hidden. Enable the "Show Canceled" filter in the calendar toolbar to view them.',
    'fin.email_report': 'Email Report',
    'fin.no_data_matches': 'No data matches current filters.',
    'fin.send_reports_title': 'Send Financial Reports',
    'fin.email_dispatched': 'Email reports have been generated and dispatched to',
    'fin.recipients': 'recipients',
    'fin.month_singular': 'month',
    'fin.months_plural': 'months',
    'builder.viz_bar': 'Bar',
    'builder.viz_stacked': 'Stacked',
    'builder.viz_line': 'Line',
    'builder.viz_pie': 'Pie',
    'builder.viz_table': 'Table',
    'builder.agg_sum': 'Sum',
    'builder.agg_average': 'Average',
    'builder.agg_count': 'Count',
    'builder.agg_min': 'Min',
    'builder.agg_max': 'Max',
    'builder.tf_today': 'Today',
    'builder.tf_current_week': 'Current Week',
    'builder.tf_current_month': 'Current Month',
    'builder.tf_custom_range': 'Custom Range',
    'builder.tf_specific_day': 'Specific Day',
    'builder.tf_specific_week': 'Specific Week',
    'builder.tf_specific_month': 'Specific Month',
    'dim.teacher': 'Teacher',
    'dim.position': 'Position',
    'dim.category': 'Category',
    'dim.tag': 'Tag',
    'dim.rate_type': 'Rate Type',
    'dim.month': 'Month',
    'dim.week': 'Week',
    'dim.day_of_week': 'Day of Week',
    'dim.room': 'Room',
    'dim.classification': 'Classification',
    'metric.active_hours': 'Active Hours',
    'metric.canceled_hours': 'Canceled Hours',
    'metric.total_hours': 'Total Hours',
    'metric.hourly_cost': 'Hourly Cost',
    'metric.global_cost': 'Global Cost',
    'metric.total_cost': 'Total Cost',
    'metric.event_count': 'Event Count',
    'metric.teacher_count': 'Teacher Count',
    'metric.avg_rate': 'Average Rate',
    'super.add_btn': 'Add',
    'super.switch_bulk': 'Switch to Bulk CSV Entry',
    'super.switch_single': 'Switch to Single Entry',
    'super.role_viewer': 'Viewer',
    'super.role_admin': 'Admin',
    'super.tools_notice': 'These tools are exclusively available to the Super Admin. No tenant admin can access them.',
    'super.wipe_data': 'Wipe Data',
    'settings.connect_account': 'Connect My Account',
    'fin.rate_hourly': 'Hourly',
    'fin.rate_global': 'Global Monthly',
    'app.something_wrong': 'Something went wrong.',
    'app.collapse_sidebar': 'Collapse Sidebar',
    'app.not_found': 'Not found',
    'app.confirm_wipe': 'Are you sure you want to permanently delete all Teachers, Rooms, Events, and Gantt data? This cannot be undone.',
    'app.reload': 'Reload App',
    'sa.restore': 'Restore',
    'cal.confirm_delete_event': 'Are you sure you want to delete this event?',
    'cal.confirm_delete_gantt': 'Delete this Gantt block? This may affect blackouts.',
    'cal.occurrences': 'occurrences',
    'chart.no_data_filters': 'No data matches the current filters',
    'builder.filters_applied': 'filters applied',
    'builder.narrow_desc': 'Narrow chart data by specific teachers, positions, tags, or categories',
    'gantt.confirm_delete_block': 'Delete this block? If it is a blackout, events will be restored.',
    'lists.confirm_remove': 'from lists? Existing records using this will not be updated.',
    'lists.remove_word': 'Remove',
    'rooms.confirm_delete': 'Are you sure? Scheduled events will flag warnings.',
    'teachers.confirm_delete': 'Are you sure you want to delete this teacher? Associated events will show warnings.',
    'teachers.confirm_bulk_delete': 'teachers? This cannot be undone.',
    'teachers.confirm_bulk_prefix': 'Are you sure you want to delete',
    'super.confirm_delete_org': 'Are you sure you want to delete the entire organization',
    'super.delete_org_warn': 'This will not delete Firestore data, only the admin record.',
    'super.confirm_change_slug': 'WARNING: Changing the tenant ID will migrate all Firestore data. Continue?',
    'super.confirm_revoke': 'Are you sure you want to revoke access for',
    'super.id_label': 'ID:',
    'super.csv_format': 'email, organization_slug, role',
    'super.confirm_snapshot': 'Would you like to take a Snapshot of current state before generating test data?',
    'super.confirm_generate': 'Generate test data? This will overwrite current data in this workspace.',
    'super.confirm_restore': 'Restore snapshot? Current changes will be overwritten!',
    'super.confirm_cal_test': 'Run Calendar Test Generator? Current state will be cleared. (Snapshot taken automatically)',
    'super.confirm_teacher_test': 'Run Teacher Test Generator? Current teachers will be replaced. (Snapshot taken automatically)',
    'settings.currency_ils': '₪ — Israeli New Shekel (ILS)',
    'settings.currency_usd': '$ — US Dollar (USD)',
    'settings.currency_eur': '€ — Euro (EUR)',
    'settings.currency_gbp': '£ — British Pound (GBP)',
    'settings.currency_jpy': '¥ — Japanese Yen (JPY)',
    'settings.currency_inr': '₹ — Indian Rupee (INR)',
    'settings.currency_btc': '₿ — Bitcoin (BTC)',
    'settings.time_12h': '12-hour (1:00 PM)',
    'settings.time_24h': '24-hour (13:00)',
    'settings.choose_calendar': '-- Choose a calendar --',
    'settings.hebrew_lang': 'עברית (Hebrew)',
    'settings.diff_account': 'Different account — sync inactive for you',
    'settings.sync_note': 'Events will only sync to Google Calendar when the designated admin is logged in. Only that account can modify the calendar configuration.',
    'fin.header_teacher': 'Teacher',
    'fin.header_position': 'Position',
    'fin.header_rate_type': 'Rate Type',
    'fin.header_rate': 'Rate',
    'fin.header_active_hrs': 'Active Hours',
    'fin.header_canceled_hrs': 'Canceled Hours',
    'fin.header_hourly_cost': 'Hourly Cost',
    'fin.header_oneoff': 'One-Off Payments',
    'fin.header_global_cost': 'Global Cost',
    'fin.header_total_cost': 'Total Cost',
    'fin.per_hr': '/hr',
    'fin.per_mo': '/mo',
    'nav.gantt.subtitle': 'Manage semesters & blackouts.',
    'gantt.blackout_label': 'Blackout',
    'gantt.no_periods': 'No periods defined.',
    'gantt.edit_period': 'Edit Period',
    'gantt.add_period': 'Add Gantt / Blackout Period',
    'gantt.blackout_warning': 'Caution: Existing events in this range will be hidden.',
    'gantt.save_changes': 'Save Changes',
    'gantt.create_apply': 'Create & Apply',
    'recurrence.on_day_of_month': 'On the {ordinal} of each month',
    'recurrence.on_pos_day_of_month': 'On the {pos} {dayName} of each month',
    'recurrence.ordinal_st': 'st',
    'recurrence.ordinal_nd': 'nd',
    'recurrence.ordinal_rd': 'rd',
    'recurrence.ordinal_th': 'th',
    'recurrence.pos_1st': '1st',
    'recurrence.pos_2nd': '2nd',
    'recurrence.pos_3rd': '3rd',
    'recurrence.pos_4th': '4th',
    'recurrence.pos_5th': '5th',
    'recurrence.day_sunday': 'Sunday',
    'recurrence.day_monday': 'Monday',
    'recurrence.day_tuesday': 'Tuesday',
    'recurrence.day_wednesday': 'Wednesday',
    'recurrence.day_thursday': 'Thursday',
    'recurrence.day_friday': 'Friday',
    'recurrence.day_saturday': 'Saturday',
    'recurrence.after': 'After',
    'recurrence.edit_series_title': 'Edit Recurring Event',
    'recurrence.delete_series_title': 'Delete Recurring Event',
    'recurrence.restore_series_title': 'Restore Recurring Event',
    'recurrence.cancel_series_title': 'Cancel Recurring Event',
    'recurrence.series_desc_edit': 'This is part of a recurring series. What would you like to edit?',
    'recurrence.series_desc_delete': 'This is part of a recurring series. What would you like to delete?',
    'recurrence.series_desc_restore': 'This is part of a recurring series. What would you like to restore?',
    'recurrence.series_desc_cancel': 'This is part of a recurring series. What would you like to cancel?',
    'recurrence.just_this_one': 'Just This One',
    'recurrence.all_events': 'All Events',
    'room.itinerary_equipment': 'Itinerary & Equipment',
    'room.empty_state': 'No rooms configured. Add one to get started.',
    'lists.add_placeholder': 'Add {title}...',
    'lists.found_items': 'Found {count} new unique items.',
    'teach.err_no_position': 'Please add at least one position with a name.',
    'teach.err_color_taken': 'This color is already assigned to another teacher. Please select a unique color.',
    'teach.found_prefix': 'Found',
    'builder.active_badge': 'ACTIVE',
    'builder.data_filters_desc': 'Narrow chart data by specific teachers, positions, tags, or categories',
    'builder.preview_summary': '{events} events · {dim} × {metrics} metric(s) → {viz}',
    'builder.n_events': '({count} events)',
    'builder.primary_label': 'Primary',
    'builder.footer_summary': '{dim} × {metrics} metric(s) → {viz}',
    'builder.footer_filters': ' · {count} filter(s)',
  },
  'he-IL': {
    'app.title': 'מרכז המוזיקה אלפרט',
    'app.subtitle': 'מערכת ניהול',
    'nav.calendar': 'לוח שנה חכם',
    'nav.gantt': 'גאנט וחסימות',
    'nav.teachers': 'מורים',
    'nav.rooms': 'חדרים',
    'nav.lists': 'ניהול רשימות',
    'nav.manage': 'ניהול',
    'nav.financial': 'דשבורד פיננסי',
    'nav.settings': 'הגדרות',
    'nav.power_tools': 'כלים מתקדמים',
    'nav.analysis': 'ניתוח פיננסי',
    'nav.super_admin': 'מנהל-על',
    'nav.mobile_access': 'גישה מנייד',
    'ops': 'תפעול',
    'admin': 'ניהול',
    'analytics': 'אנליטיקה',
    'today': 'היום',
    // Buttons
    'btn.add': 'הוסף',
    'btn.create': 'צור',
    'btn.save': 'שמור',
    'btn.cancel': 'ביטול',
    'btn.delete': 'מחק',
    'btn.close': 'סגור',
    'btn.confirm': 'אישור',
    'btn.back': 'חזור',
    'btn.export': 'ייצוא',
    'btn.import': 'ייבא',
    'btn.clear_all': 'נקה הכל',
    'btn.sign_out': 'יציאה',
    'btn.connect_account': 'חבר את החשבון שלי',
    'btn.disconnect': 'נתק',
    'btn.reconnect': 'חבר מחדש',
    'btn.save_insight': 'שמור תובנה',
    'btn.download_report': 'הורד דוח (CSV)',
    // Calendar view
    'mode.day': 'יום',
    'mode.week': 'שבוע',
    'mode.month': 'חודש',
    'mode.list': 'רשימה',
    'filter.teacher': 'מורה: הכל',
    'filter.room': 'חדר: הכל',
    'filter.type': 'סוג: הכל',
    'filter.category_all': 'קטגוריה: הכל',
    'filter.no_filters': 'ללא פילטרים',
    'filter.show_canceled': 'הצג אירועים מבוטלים',
    'filter.show_blackouts': 'הצג חסימות',
    'filter.all_teachers': 'כל המורים',
    'filter.all_categories': 'כל הקטגוריות',
    'filter.all_types': 'כל הסוגים',
    'filter.all_tags': 'כל התגיות',
    'filter.by_position': 'סנן לפי תפקיד',
    'filter.by_tag': 'סנן לפי תגית',
    // Event modal
    'modal.add_event': 'הוסף אירוע',
    'modal.edit_event': 'ערוך אירוע',
    'label.name': 'שם האירוע',
    'label.desc': 'תיאור',
    'label.teacher': 'מורה',
    'label.room': 'חדר',
    'label.type': 'סוג',
    'label.start': 'התחלה',
    'label.end': 'סיום',
    'label.date': 'תאריך',
    'label.position': 'תפקיד',
    'label.recurrence': 'חזרתיות',
    'label.full_name': 'שם מלא',
    'label.teacher_color': 'צבע המורה',
    'label.category': 'קטגוריה',
    'label.rate_type': 'סוג תעריף',
    'label.room_name': 'שם החדר',
    'label.itinerary_desc': 'תיאור / ציוד',
    'label.from': 'מ-',
    'label.to': 'עד',
    'label.optional': '(אופציונלי)',
    'label.requires_teacher': '(דורש מורה ותפקיד)',
    'label.live': 'חי',
    'label.no_room': 'ללא חדר',
    'label.no_room_dash': '— ללא חדר —',
    // Calendar states
    'cal.canceled': 'מבוטל',
    'cal.no_events': 'אין אירועים',
    'cal.hide_canceled': 'הסתר מבוטלים',
    'cal.hide_blackouts': 'הסתר חסימות',
    'cal.recurring_event': 'אירוע מחזורי',
    'cal.every': 'כל',
    'cal.on_days': 'בימים',
    'cal.monthly_mode': 'מחזוריות חודשית',
    'cal.mark_canceled': 'סמן כמבוטל',
    'cal.cancel_pay_status': 'סטטוס תשלום ביטול',
    'cal.no_pay': 'ללא תשלום',
    'cal.paid_cancel': 'ביטול בתשלום',
    'cal.delete_event': 'מחק אירוע',
    'cal.payment_method': 'שיטת תשלום',
    'cal.select_category': 'בחר קטגוריה',
    'cal.save_changes': 'שמור שינויים',
    'cal.save_update_series': 'שמור ועדכן סדרה',
    'cal.update_this_only': 'עדכן רק את זה',
    'cal.update_all_future': 'עדכן את כל העתידיים',
    'cal.recurring_series_msg': 'זהו אירוע מתוך סדרה חוזרת. מה תרצה לעשות',
    'cal.this_event_only': 'אירוע זה בלבד',
    'cal.this_and_future': 'אירוע זה וכל הבאים',
    'cal.all_in_series': 'כל האירועים בסדרה',
    // Calendar recurrence
    'recurrence.none': 'ללא חזרה',
    'recurrence.daily': 'יומי',
    'recurrence.weekly': 'שבועי',
    'recurrence.biweekly': 'דו-שבועי',
    'recurrence.monthly': 'חודשי',
    'recurrence.yearly': 'שנתי',
    'recurrence.until': 'עד תאריך',
    'recurrence.ends_after': 'מסתיים לאחר',
    'recurrence.ends_on': 'מסתיים בתאריך',
    'recurrence.occurrences': 'מופעים',
    // Settings
    'settings.general': 'הגדרות כלליות',
    'settings.integrations': 'אינטגרציות',
    'settings.dev_tools': 'כלי מפתח',
    'settings.generate_data': 'יצירת נתוני בדיקה',
    'settings.generate_data_desc': 'אכלוס הלוח עם 20 מורים ואירועים אקראיים.',
    'settings.generate_btn': 'צור נתונים',
    'settings.unsaved': 'ישנם שינויים שלא נשמרו',
    'settings.testing_tools': 'כלי בדיקה',
    'settings.currency': 'מטבע',
    'settings.currency_symbol': 'סמל מטבע',
    'settings.currency_desc': 'סמל זה יופיע ליד כל ערכי העלות בדשבורד הפיננסי, הניתוח והייצוא.',
    'settings.gcal_sync': 'סנכרון יומן Google',
    'settings.gcal_desc': 'דחיפת שיעורים מתוזמנים ליומן Google של מנהל הארגון.',
    'settings.connected_via': 'מחובר דרך',
    'settings.sync_inactive': 'חשבון אחר — סנכרון לא פעיל עבורך',
    'settings.token_expired': 'אסימון האימות פג תוקף. חבר מחדש כדי לשחזר את הסנכרון.',
    'settings.fetching_cals': 'מביא את היומנים שלך...',
    'settings.select_calendar': 'בחר יומן יעד',
    'settings.choose_cal': '— בחר יומן —',
    'settings.primary': '(ראשי)',
    'settings.auto_add_desc': 'שיעורים חדשים יתווספו אוטומטית ליומן זה.',
    'settings.sync_managed_by': 'סנכרון היומן מנוהל על ידי {email}',
    'settings.sync_condition': 'אירועים יסתנכרנו ליומן Google רק כאשר המנהל ({email}) מחובר.',
    'settings.admin_only': 'מנהלים בלבד',
    'settings.managed_by_admin': 'מנוהל על ידי מנהל הארגון',
    'settings.week_hidden': 'מוסתר',
    'settings.week_number': 'מספר שבוע',
    'settings.week_of': 'שבוע של...',
    // Labels
    'label.default_lang': 'שפת מערכת',
    'label.system_default': 'ברירת מחדל של המערכת',
    'label.coming_soon': 'בקרוב',
    'label.timezone': 'אזור זמן',
    'label.date_format': 'פורמט תאריך',
    'label.time_format': 'פורמט שעה',
    'label.calendar_defaults': 'הגדרות יומן ברירת מחדל',
    'label.default_duration': 'משך אירוע ברירת מחדל (דקות)',
    'label.week_numbers': 'תצוגת מספרי שבועות',
    'label.blackout': 'חסימה',
    // Nav sections
    'nav.section.localization': 'לוקליזציה',
    'nav.section.date_time': 'תאריך ושעה',
    'nav.section.analytics': 'אנליטיקה',
    'nav.section.operations': 'תפעול',
    'nav.section.admin': 'ניהול',
    // Roles
    'role.admin': 'מנהל',
    'role.viewer': 'צופה',
    // Alerts
    'alert.confirm_generate': 'פעולה זו תדרוס מורים ואירועים קיימים. להמשיך?',
    'alert.data_generated': 'נתונים נוצרו בהצלחה!',
    'alert.delete_event': 'האם למחוק את האירוע?',
    'alert.delete_gantt': 'למחוק בלוק זה? הפעולה עשויה להשפיע על חסימות.',
    'alert.end_time_error': 'שעת הסיום חייבת להיות אחרי שעת ההתחלה',
    'alert.delete_teacher': 'האם למחוק מורה זה? אירועים קשורים יציגו אזהרות.',
    'alert.delete_room': 'האם אתה בטוח? אירועים מתוזמנים יציגו אזהרות.',
    'alert.delete_gantt_block': 'למחוק בלוק זה? אם זו חסימה, האירועים ישוחזרו.',
    'alert.error_reading_file': 'שגיאה בקריאת הקובץ',
    'alert.no_valid_teachers': 'לא נמצאו מורים תקינים או חדשים ב-CSV.',
    'alert.no_valid_rows': 'לא נמצאו שורות תקינות. ודא שהתאריכים בפורמט YYYY-MM-DD או DD/MM/YYYY.',
    'alert.csv_parse_fail': 'שגיאה בניתוח קובץ CSV.',
    'alert.delete_all_data': 'האם אתה בטוח שברצונך למחוק לצמיתות את כל הנתונים ממרחב העבודה הזה בענן?',
    'alert.action_cannot_undo': 'לא ניתן לבטל פעולה זו.',
    // Power Tools
    'pt.bulk_delete': 'מחיקה מרוכזת',
    'pt.date_range': 'טווח תאריכים',
    'pt.criteria': 'קריטריונים לסינון',
    'pt.preview': 'תצוגה מקדימה',
    'pt.delete_all': 'מחק הכל',
    'pt.confirm_delete': 'נא לאשר מחיקה של {count} אירועים.',
    'pt.success': 'נמחקו {count} אירועים בהצלחה.',
    'pt.no_matches': 'לא נמצאו אירועים מתאימים.',
    'pt.time_range': 'טווח זמן',
    'pt.interactive': 'בחירה אינטראקטיבית',
    'pt.import_csv': 'ייבוא מערכת שעות מ-CSV',
    // Financial Dashboard
    'fin.title': 'לוח בקרה פיננסי',
    'fin.all_time': 'כל הזמנים',
    'fin.grand_total': 'סה"כ כולל',
    'fin.hourly_fees': 'תעריפים שעתיים',
    'fin.global_monthly': 'חודשי גלובלי',
    'fin.active_hours': 'שעות פעילות',
    'fin.canceled': 'מבוטלים',
    'fin.teacher_metrics': 'מדדי מורים',
    'fin.sort_hint': '· לחץ על הכותרות למיון',
    'fin.current_week': 'השבוע הנוכחי',
    'fin.daily': 'יומי',
    'fin.hourly': 'שעתי',
    'fin.weekly': 'שבועי',
    'fin.monthly': 'חודשי',
    'fin.revenue_trend': 'מגמת הכנסות',
    // Table headers
    'col.name': 'שם',
    'col.active_hrs': 'שעות פעילות',
    'col.canceled_hrs': 'שעות מבוטלות',
    'col.cancel_count': 'מס\' ביטולים',
    'col.hourly_cost': 'עלות שעתית',
    'col.one_off_cost': 'עלות חד-פעמית',
    'col.global_cost': 'עלות גלובלית',
    'col.total': 'סה"כ',
    'col.recipient': 'נמען',
    'col.email_address': 'כתובת אימייל',
    'col.total_payout': 'סה"כ תשלום',
    'col.positions_rates': 'תפקידים ותעריפים',
    'col.contact': 'פרטי קשר',
    'col.rates': 'תעריפים',
    'col.entry_name': 'שם הרשומה',
    'col.actions': 'פעולות',
    // Financial Analysis
    'fin_ana.title': 'ניתוח פיננסי',
    'fin_ana.delete_chart': 'מחק תרשים',
    'fin_ana.insight_title': 'כותרת תובנה',
    'fin_ana.metric': 'מדד',
    'fin_ana.total_active_hours': 'סה"כ שעות פעילות',
    'fin_ana.total_canceled_hours': 'סה"כ שעות מבוטלות',
    'fin_ana.hourly_payroll': 'שכר שעתי',
    'fin_ana.global_payroll': 'שכר גלובלי',
    'fin_ana.grand_total_payroll': 'סה"כ שכר',
    'fin_ana.avg_hours_teacher': 'ממוצע שעות למורה',
    'fin_ana.avg_payroll_teacher': 'ממוצע שכר למורה',
    'fin_ana.cancel_rate': 'שיעור ביטולים',
    'fin_ana.highest_earner': 'המשתכר הגבוה',
    'fin_ana.lowest_earner': 'המשתכר הנמוך',
    'fin_ana.choose_insights': 'בחר תובנות לתצוגה',
    'fin_ana.no_insights': 'לא נבחרו תובנות. לחץ על ערוך כדי לבחור אילו תובנות להציג.',
    'fin_ana.create_first_chart': 'צור את התרשים המותאם הראשון שלך',
    'fin_ana.back_to_dashboard': 'חזרה לדשבורד',
    'fin_ana.classify_desc': 'קבץ נתונים לפי קטגוריה (טווחי זמן נשלטים בנפרד למטה)',
    'fin_ana.select_period_desc': 'בחר את תקופת הזמן לניתוח (ללא קשר להקבצה)',
    // Teacher Manager
    'teach.title': 'ניהול מורים',
    'teach.add': 'הוסף מורה',
    'teach.import_title': 'ייבוא מורים',
    'teach.import_csv': 'ייבוא מורים מקובץ CSV',
    'teach.csv_columns': 'בחר קובץ .csv עם העמודות: שם, אימייל, טלפון, תגיות',
    'teach.colors_auto': '* צבעים יוקצו אוטומטית',
    'teach.add_first_position': '+ הוסף תפקיד ראשון',
    'teach.position_assignment': 'שיוך תפקיד',
    'teach.select_to_import': 'בחר מורים לייבוא',
    'teach.unique_teachers': 'מורים ייחודיים. בחר את אלו שברצונך לייבוא.',
    'teach.selected': 'נבחרו',
    'teach.already_in_list': 'כבר ברשימה',
    'teach.skip': 'דלג',
    'teach.no_teachers_found': 'לא נמצאו מורים בקובץ זה.',
    'teach.back_to_list': 'חזרה לרשימה',
    // Room Manager
    'room.title': 'ניהול חדרים',
    'room.itinerary': 'ציוד ואביזרים',
    // Gantt
    'gantt.title': 'סמסטרים וחופשות',
    'gantt.subtitle': 'ניהול סמסטרים וחופשות.',
    'gantt.label_title': 'כותרת',
    'gantt.start_date': 'תאריך התחלה',
    'gantt.end_date': 'תאריך סיום',
    'gantt.display_color': 'צבע תצוגה',
    'gantt.apply_blackout': 'החל חסימה',
    'gantt.blackout_desc': 'הסתר אוטומטית את כל האירועים בטווח זה מהיומן ומהדוחות.',
    // Chart Builder
    'chart.title_label': 'כותרת התרשים',
    'chart.filter_mode': 'מצב סינון',
    'chart.live': 'חי',
    'chart.live_desc': 'מגיב לפילטרי הדשבורד',
    'chart.snapshot': 'תמונת מצב',
    'chart.snapshot_desc': 'מקפיא פילטרים בעת השמירה',
    'chart.sort_by': 'מיין לפי',
    'chart.dimension_label': 'תווית מימד',
    'chart.ascending': 'עולה',
    'chart.descending': 'יורד',
    'chart.no_options': 'אין אפשרויות זמינות',
    'chart.add_position': 'הוספת תפקיד',
    'chart.position_name': 'שם התפקיד',
    'chart.select_icon': 'בחר אייקון',
    'chart.choose_icon': 'בחר אייקון לתפקיד זה',
    // Filter sections
    'filter.teachers': 'מורים',
    'filter.positions': 'תפקידים',
    'filter.tags': 'תגיות',
    'filter.categories': 'קטגוריות',
    'filter.rate_type': 'סוג תעריף',
    // Manage Lists
    'lists.title': 'רשימות בחירה',
    'lists.desc': 'עדכן את האפליקציה שלך על ידי שינוי רשימות אלו.',
    'lists.classifications': 'סיווגים',
    'lists.how_to': 'איך להשתמש בכלי זה:',
    'lists.step1': '1. מלא את הנתונים למטה',
    'lists.step2': '2. ייצא ל-CSV',
    'lists.step3': '3. פתח באפליקציה שלך',
    'lists.add_row': 'הוסף שורה',
    'lists.template': 'תבנית',
    // Auth
    'auth.sign_in_google': 'התחבר עם Google',
    'auth.workspaces': 'סביבות עבודה מורשות',
    'auth.no_workspaces': 'לא נמצאו סביבות עבודה מורשות.',
    'auth.signing_in': 'מתחבר לענן Cadenza...',
    // Tooltips
    'tooltip.edit': 'ערוך',
    'tooltip.duplicate': 'שכפל',
    'tooltip.delete': 'מחק',
    'tooltip.switch_light': 'עבור למצב בהיר',
    'tooltip.switch_dark': 'עבור למצב כהה',
    'tooltip.expand_sidebar': 'הרחב תפריט צד',
    'tooltip.collapse_sidebar': 'כווץ תפריט צד',
    'tooltip.open_menu': 'פתח תפריט',
    'tooltip.add_event': 'לחץ להוספת אירוע',
    'tooltip.toggle_filters': 'הצג/הסתר פילטרים',
    'tooltip.remove_position': 'הסר תפקיד',
    // Placeholders
    'placeholder.search_teachers': 'חפש מורים...',
    'placeholder.or_type_new': 'או הקלד חדש...',
    'placeholder.event_name': 'לדוגמה: שיעור פסנתר',
    'placeholder.room_details': 'פרטים על ציוד, קיבולת וכדומה',
    'placeholder.choose_calendar': '— בחר יומן —',
    // Dynamic
    'dynamic.rate_hourly': 'תעריף ({currency}/שעה)',
    'dynamic.monthly_fee': 'דמי חודשי ({currency})',
    'dynamic.send_reports': 'שלח {n} דוחות',
    'dynamic.week_of': 'שבוע של {date}',
    'dynamic.hourly_currency': 'שעתי ({currency})',
    'dynamic.one_off_currency': 'חד-פעמי ({currency})',
    'dynamic.global_currency': 'גלובלי ({currency})',
    'dynamic.total_currency': 'סה"כ ({currency})',
    'dynamic.one_off_price': 'מחיר חד-פעמי ({currency})',
    // Footer
    'footer.copyright': '© 2026 מרכז המוזיקה',
    // Super Admin
    'super.title': 'מנהל-על',
    'super.delete_all': 'מחק את כל הנתונים',
    // ── Auto-inserted missing translations (Phase 2 repair) ──
    'agg.average': 'ממוצע',
    'agg.count': 'ספירה',
    'agg.max': 'מקסימום',
    'agg.min': 'מינימום',
    'agg.sum': 'סכום',
    'analysis.advanced_filters': 'פילטרים מתקדמים',
    'analysis.back_to_dashboard': 'חזרה לדשבורד',
    'analysis.charts': 'תרשימים',
    'analysis.choose_insights': 'בחר תובנות גלויות',
    'analysis.clear_all': 'נקה הכל',
    'analysis.click_edit': 'לחץ על עריכה לבחירת התובנות שיוצגו.',
    'analysis.create_first_chart': 'צור את התרשים המותאם הראשון שלך',
    'analysis.create_first_chart_desc': 'קבץ נתונים לפי כל ממד, בחר מדדים, ובחר סוג הצגה',
    'analysis.custom_insight': 'תובנה מותאמת',
    'analysis.filters': 'פילטרים',
    'analysis.key_insights': 'תובנות מפתח',
    'analysis.new_chart': 'תרשים חדש',
    'analysis.no_insights': 'לא נבחרו תובנות.',
    'analysis.open_menu': 'פתח תפריט',
    'analysis.show_all': 'הצג הכל',
    'analysis.subtitle': 'תובנות, תרשימים, השוואות, וחקירת נתונים מעמיקה.',
    'analysis.title': 'ניתוח פיננסי',
    'builder.active': 'פעיל:',
    'builder.add': 'הוסף',
    'builder.add_another': 'הוסף השוואה נוספת',
    'builder.advanced': 'אפשרויות מתקדמות',
    'builder.applied': 'מוחל',
    'builder.ascending': 'עולה',
    'builder.by': 'לפי',
    'builder.cancel': 'ביטול',
    'builder.category_ies': 'קטגוריה/ות',
    'builder.chart_title': 'כותרת התרשים',
    'builder.chart_title_placeholder': 'לדוגמה: מגמת עלויות חודשית, שעות לפי מחלקה...',
    'builder.clear_all_filters': 'נקה את כל המסננים',
    'builder.comparison_active': 'מצב השוואה פעיל — הוסף תקופות להשוואה מול מסגרת הזמן הראשית',
    'builder.comparison_inactive': 'השווה את אותם מסננים מול תקופות שונות מאותו סוג מסגרת זמן',
    'builder.comparison_mode': 'מצב השוואה',
    'builder.comparison_n': 'השוואה',
    'builder.create_chart': 'צור תרשים מותאם',
    'builder.custom_range': 'טווח מותאם',
    'builder.data_filters': 'מסנני נתונים',
    'builder.descending': 'יורד',
    'builder.dimension_label': 'תווית ממד',
    'builder.edit_chart': 'עריכת תרשים',
    'builder.events': 'אירועים',
    'builder.events_in_timeframe': 'אירועים במסגרת הזמן הנבחרת',
    'builder.filter': 'מסנן',
    'builder.filter_desc': 'צמצם נתוני תרשים לפי מורים, תפקידים, תגיות או קטגוריות ספציפיים',
    'builder.filter_mode': 'מצב מסנן',
    'builder.filters_word': 'מסננים',
    'builder.group_by': 'קיבוץ לפי',
    'builder.group_by_desc': 'סווג נתונים לפי קטגוריה (מסגרות הזמן נשלטות בנפרד למטה)',
    'builder.grouped_series': 'סדרות מקובצות',
    'builder.limit_topn': 'הגבלה (N עליונים)',
    'builder.live': 'חי',
    'builder.live_desc': 'מגיב למסנני לוח הבקרה',
    'builder.live_preview': 'תצוגה מקדימה חיה',
    'builder.merged': 'ממוזג',
    'builder.merged_overlay': 'שכבה ממוזגת',
    'builder.metric': 'מדד',
    'builder.metrics': 'מדדים',
    'builder.metrics_displayed': 'מדדים — מוצגים כ',
    'builder.metrics_word': 'מדדים',
    'builder.no_limit': '0 = ללא הגבלה',
    'builder.pick_date_desired_week': 'בחר כל תאריך בשבוע הרצוי:',
    'builder.pick_date_in_week': 'בחר תאריך בשבוע ההשוואה:',
    'builder.position_s': 'תפקיד/ים',
    'builder.preview': 'תצוגה מקדימה',
    'builder.primary': 'ראשי',
    'builder.rate_type_s': 'סוג/י תעריף',
    'builder.save_chart': 'שמור תרשים',
    'builder.select_comparison_day': 'בחר יום להשוואה:',
    'builder.select_comparison_month': 'בחר חודש להשוואה:',
    'builder.select_comparison_range': 'בחר טווח תאריכים להשוואה:',
    'builder.select_period': 'בחר תקופה',
    'builder.show_all': '0 = הצג את כל הקבוצות',
    'builder.side_by_side': 'זה לצד זה',
    'builder.side_by_side_label': 'זה לצד זה',
    'builder.snapshot': 'תמונת מצב',
    'builder.snapshot_desc': 'מקפיא מסננים בזמן השמירה',
    'builder.sort_by': 'מיון לפי',
    'builder.stacked_segments': 'מקטעים מוערמים',
    'builder.tag_s': 'תגית/ות',
    'builder.teacher_s': 'מורה/ים',
    'builder.timeframe': 'מסגרת זמן',
    'builder.timeframe_desc': 'בחר את תקופת הזמן לניתוח (בלתי תלוי בקיבוץ)',
    'builder.title': 'בונה תרשימים',
    'builder.to': 'עד',
    'builder.update_chart': 'עדכן תרשים',
    'builder.visualization': 'ויזואליזציה',
    'builder.week_of': 'שבוע של',
    'cal.add_event': 'הוספת אירוע',
    'cal.aria_toggle_blackouts': 'החלף נראות אירועי חסימה',
    'cal.aria_toggle_canceled': 'החלף נראות אירועים מבוטלים',
    'cal.blackout_period': 'תקופת חסימה',
    'cal.click_add': 'לחץ להוספת אירוע',
    'cal.daily': 'יומי',
    'cal.day': 'יום',
    'cal.description': 'תיאור',
    'cal.detail.cancel_event': 'ביטול',
    'cal.detail.delete': 'מחיקה',
    'cal.detail.edit': 'עריכה',
    'cal.detail.restore': 'שחזור',
    'cal.edit_event': 'עריכת אירוע',
    'cal.end': 'סיום',
    'cal.event_name': 'שם האירוע',
    'cal.filter.position_all': 'תפקיד: הכל',
    'cal.filter.room_all': 'חדר: הכל',
    'cal.filter.tag_all': 'תגית: הכל',
    'cal.filter.teacher_all': 'מורה: הכל',
    'cal.filter.type_all': 'סוג: הכל',
    'cal.month': 'חודש',
    'cal.monthly': 'חודשי',
    'cal.no_repeat': 'לא חוזר',
    'cal.part_of_series': 'חלק מסדרה',
    'cal.recurrence': 'חזרה',
    'cal.recurring': 'חוזר',
    'cal.room': 'חדר',
    'cal.start': 'התחלה',
    'cal.teacher': 'מורה',
    'cal.today': 'היום',
    'cal.toggle_filters': 'החלף מסננים',
    'cal.type': 'סוג',
    'cal.unnamed': 'אירוע ללא שם',
    'cal.week': 'שבוע',
    'cal.week_num': 'שבוע',
    'cal.week_of': 'שבוע של',
    'cal.weekly': 'שבועי',
    'cal.yearly': 'שנתי',
    'chart.delete': 'מחיקה',
    'chart.done': 'סיום',
    'chart.duplicate': 'שכפול',
    'chart.edit': 'עריכה',
    'chart.updated': 'עודכן',
    'common.cancel': 'ביטול',
    'common.close': 'סגירה',
    'common.delete': 'מחיקה',
    'common.edit': 'עריכה',
    'common.not_found': 'לא נמצא',
    'common.sandbox': 'ארגז חול',
    'common.save': 'שמירה',
    'common.sign_out': 'התנתקות',
    'dropdown.all': 'הכל',
    'dropdown.clear': 'נקה',
    'dropdown.no_options': 'אין אפשרויות זמינות',
    'dropdown.select_all': 'בחר הכל',
    'dropdown.selected': 'נבחרו',
    'event.category': 'קטגוריה',
    'event.description_label': 'תיאור',
    'event.edit': 'עריכת אירוע',
    'event.end_time': 'שעת סיום',
    'event.general_events': 'אירועים כלליים',
    'event.group_lesson': 'שיעור קבוצתי',
    'event.individual_lesson': 'שיעור פרטי',
    'event.name': 'שם האירוע',
    'event.name_placeholder': 'לדוגמה: שיעור פסנתר',
    'event.new': 'אירוע חדש',
    'event.no_payment': 'ללא תשלום (תזמון בלבד)',
    'event.no_positions': 'אין תפקידים זמינים למורה זה תחת קטגוריה זו',
    'event.no_room': 'ללא חדר',
    'event.one_off_payment': 'תשלום חד פעמי',
    'event.one_off_price': 'מחיר חד פעמי',
    'event.optional': '(אופציונלי)',
    'event.org_no_teacher': 'ארגון / ללא מורה (אופציונלי)',
    'event.payment_method': 'שיטת תשלום',
    'event.position': 'תפקיד',
    'event.requires_teacher_position': '(דורש מורה ותפקיד)',
    'event.room': 'חדר',
    'event.select_category': 'בחר קטגוריה',
    'event.select_category_first': 'בחר קטגוריה קודם',
    'event.select_position': 'בחר תפקיד',
    'event.select_teacher': 'בחר מורה',
    'event.select_teacher_first': 'בחר מורה קודם',
    'event.start_time': 'שעת התחלה',
    'event.teacher': 'מורה',
    'event.teacher_lessons': 'שיעורי מורה',
    'event.use_position_rate': 'השתמש בתעריף תפקיד',
    'filter.global_monthly': 'גלובלי חודשי',
    'filter.hourly': 'שעתי',
    'filter.rate_types': 'סוגי תעריפים',
    'financial.delete_title': 'מחיקה',
    'gantt.delete': 'מחיקה',
    'insight.active_teachers': 'מורים פעילים',
    'insight.avg_cost': 'עלות ממוצעת / מורה',
    'insight.cancel_rate': 'אחוז ביטולים',
    'insight.cost_split': 'שעתי מול גלובלי',
    'insight.highest_payroll': 'שכר הכי גבוה',
    'insight.lowest_payroll': 'שכר הכי נמוך',
    'insight.most_active_position': 'תפקיד הכי פעיל',
    'insight.most_canceled': 'הכי הרבה שעות מבוטלות',
    'insight.most_hours': 'הכי הרבה שעות הוראה',
    'insight.most_positions': 'הכי הרבה תפקידים',
    'insight.no_cancellations': 'אין ביטולים',
    'insight.no_data': 'אין נתונים',
    'insight.of_active_hours': 'מכל השעות הפעילות',
    'insight.of_their_hours': 'מסך כל השעות שלהם',
    'insight.of_total': 'מהסך הכל',
    'insight.of_total_payroll': 'מסך כל השכר',
    'insight.top_position': 'תפקיד מוביל (שעות)',
    'lists.configure_desc': 'הגדר אפשרויות תפריט נפתח גלובליות עבור תפקידים, תגיות וסיווגים.',
    'lists.import_all': 'ייבוא הכל',
    'lists.import_csv': 'ייבוא CSV',
    'lists.import_preview': 'תצוגה מקדימה לייבוא',
    'lists.manage_title': 'ניהול רשימות',
    'lists.new_classifications': 'סיווגים חדשים',
    'lists.new_positions': 'תפקידים חדשים',
    'lists.new_tags': 'תגיות חדשות',
    'lists.no_items': 'לא נמצאו פריטים',
    'lists.positions': 'תפקידים',
    'lists.tags': 'תגיות',
    'metric.all_teachers': 'כל המורים',
    'metric.avg_hours': 'ממוצע שעות למורה',
    'metric.avg_payroll': 'ממוצע שכר למורה',
    'metric.global_payroll': 'שכר גלובלי',
    'metric.grand_total': 'סהכ שכר,סהכ שכר',
    'metric.highest_earner': 'בעל ההכנסה הגבוהה ביותר',
    'metric.hourly_payroll': 'שכר שעתי',
    'metric.lowest_earner': 'בעל ההכנסה הנמוכה ביותר',
    'metric.oneoff_payroll': 'תשלום חד פעמי',
    'metric.total_active_hours': 'סהכ שעות פעילות,סהכ שעות פעילות',
    'metric.total_canceled_hours': 'סהכ שעות מבוטלות,סהכ שעות מבוטלות',
    'modal.averages_rates': 'ממוצעים ושיעורים',
    'modal.cannot_undo': 'פעולה זו אינה ניתנת לביטול.',
    'modal.confirm_delete_chart': 'האם אתה בטוח שברצונך למחוק',
    'modal.delete_chart': 'מחק תרשים',
    'modal.extremes': 'קיצוניים',
    'modal.filter_by_teacher': 'סנן לפי מורה (אופציונלי)',
    'modal.insight_title': 'כותרת התובנה',
    'modal.metric': 'מדד',
    'modal.new_insight': 'תובנה חדשה',
    'modal.save_insight': 'שמור תובנה',
    'modal.totals': 'סיכומים',
    'power.all_tags': 'כל התגיות',
    'power.all_teachers': 'כל המורים',
    'power.all_types': 'כל הסוגים',
    'recurrence.after_n': 'אחרי N חזרות',
    'recurrence.days': 'יום/ימים',
    'recurrence.ends': 'מסתיים',
    'recurrence.every': 'כל',
    'recurrence.monthly_mode': 'מצב חודשי',
    'recurrence.months': 'חודש/ים',
    'recurrence.never': 'לעולם לא',
    'recurrence.on_date': 'בתאריך',
    'recurrence.on_day_n': 'ביום',
    'recurrence.on_days': 'בימים',
    'recurrence.recurring_event': 'אירוע חוזר',
    'recurrence.weeks': 'שבוע/ות',
    'room.add': 'הוספת חדר',
    'room.add_new': 'הוספת חדר חדש',
    'room.details_placeholder': 'פרטים על ציוד, קיבולת וכו\'',
    'room.edit': 'עריכת חדר',
    'room.equipment': 'ציוד',
    'room.itinerary_desc': 'רשימת ציוד / תיאור',
    'room.no_details': 'לא סופקו פרטים.',
    'room.no_rooms': 'לא הוגדרו חדרים. הוסף אחד כדי להתחיל.',
    'settings.hidden': 'מוסתר',
    'settings.managed_by_tenant': 'מנוהל על ידי מנהל שוכר',
    'settings.mobile_access': 'גישה מניידת',
    'settings.open_menu': 'פתח תפריט',
    'speed.gantt_view': 'תצוגת גאנט',
    'speed.new_event': 'אירוע חדש',
    'speed.power_tools': 'כלים מתקדמים',
    'teacher.all_categories': 'כל הקטגוריות',
    'teacher.filter_position': 'סנן לפי תפקיד',
    'teacher.filter_tag': 'סנן לפי תגית',
    'teacher.or_type_new': 'או הקלד חדש...',
    'teacher.remove_position': 'הסר תפקיד',
    'teacher.select_from_list': 'בחר מרשימה...',
    'tf.current_month': 'חודש נוכחי',
    'tf.current_week': 'שבוע נוכחי',
    'tf.custom_range': 'טווח מותאם',
    'tf.specific_day': 'יום ספציפי',
    'tf.specific_month': 'חודש ספציפי',
    'tf.specific_week': 'שבוע ספציפי',
    'tf.today': 'היום',
    'time.all_time': 'כל הזמנים',
    'time.current_month': 'חודש נוכחי',
    'time.current_week': 'שבוע נוכחי',
    'time.custom_range': 'טווח מותאם',
    'time.specific_day': 'יום ספציפי',
    'time.specific_month': 'חודש ספציפי',
    'time.specific_week': 'שבוע ספציפי',
    'time.today': 'היום',
    'viz.bar': 'עמודות',
    'viz.line': 'קו',
    'viz.pie': 'עוגה',
    'viz.stacked': 'מוערם',
    'viz.table': 'טבלה',
    'teach.col_name': 'שם',
    'teach.col_positions': 'תפקידים ותעריפים',
    'teach.col_tags': 'תגיות',
    'teach.col_contact': 'יצירת קשר',
    'teach.col_actions': 'פעולות',
    'teach.template': 'תבנית',
    'teach.export': 'ייצוא',
    'teach.import': 'ייבוא',
    'teach.subtitle': 'נהל פרופילי מדריכים, תפקידים, תעריפים ותגיות.',
    'teach.select_position_placeholder': 'בחר תפקיד...',
    'teach.select_tag_placeholder': 'בחר תגית...',
    'teach.edit_teacher': 'עריכת מורה',
    'teach.add_new_teacher': 'הוספת מורה חדש',
    'teach.position_assignments_label': 'שיוכי תפקידים',
    'teach.add_position': 'הוסף תפקיד',
    'teach.position_name': 'שם תפקיד',
    'teach.category': 'קטגוריה',
    'teach.rate_type': 'סוג תעריף',
    'teach.hourly': 'שעתי',
    'teach.global_monthly': 'חודשי גלובלי',
    'teach.rate_hourly_label': 'תעריף',
    'teach.per_hour': '/שעה',
    'teach.monthly_fee': 'תשלום חודשי',
    'teach.no_positions_yet': 'עדיין לא שויכו תפקידים.',
    'teach.position_placeholder': 'לדוגמה: מדריך פסנתר',
    'teach.tags_label': 'תגיות',
    'teach.add_tag': 'הוסף',
    'teach.email': 'דוא"ל',
    'teach.phone': 'טלפון',
    'teach.cancel': 'ביטול',
    'teach.save': 'שמירה',
    'teach.import_teachers': 'ייבוא מורים',
    'teach.import_col_name': 'שם',
    'teach.import_col_email': 'דוא"ל',
    'teach.import_col_positions': 'תפקידים',
    'teach.import_col_rates': 'תעריפים',
    'teach.import_n_teachers': 'ייבוא',
    'teach.teachers_word': 'מורים',
    'teach.delete_selection': 'מחק בחירה',
    'sa.access_denied': 'הגישה נדחתה',
    'sa.restricted': 'אזור זה מוגבל למנהל-העל של הפלטפורמה.',
    'sa.console_title': 'מסוף מנהל-על',
    'sa.console_subtitle': 'ניהול ארגונים, הרשאות וכלי פיתוח',
    'sa.tab_orgs': 'ארגונים',
    'sa.tab_access': 'מיפויי גישה',
    'sa.tab_dev': 'כלי פיתוח',
    'sa.register_org': 'רישום ארגון חדש',
    'sa.org_name': 'שם הארגון',
    'sa.org_name_placeholder': 'לדוגמה: מרכז המוזיקה אלפרט',
    'sa.url_slug': 'מזהה URL',
    'sa.url_slug_placeholder': 'לדוגמה: alpert (ללא רווחים)',
    'sa.id_label': 'מזהה:',
    'sa.edit_org_title': 'עריכת ארגון',
    'sa.upload_logo': 'העלאת לוגו',
    'sa.delete_org': 'מחיקת ארגון',
    'sa.save_changes': 'שמור שינויים',
    'sa.cancel': 'ביטול',
    'sa.no_orgs': 'עדיין לא נרשמו ארגונים.',
    'sa.map_user': 'שיוך משתמש לארגון',
    'sa.user_email': 'דוא"ל משתמש (Gmail)',
    'sa.user_email_placeholder': 'user@gmail.com',
    'sa.organization': 'ארגון',
    'sa.select_org': 'בחר ארגון...',
    'sa.all_orgs': 'כל הארגונים',
    'sa.viewer': 'צופה',
    'sa.admin': 'מנהל',
    'sa.revoke_access': 'ביטול גישה',
    'sa.generate_test': 'יצירת נתוני בדיקה',
    'sa.state_snapshot': 'תמונת מצב',
    'sa.snapshot_desc': 'שמור נתוני אפליקציה נוכחיים באחסון הדפדפן או שחזר מתמונת מצב קודמת.',
    'sa.create_snapshot': 'צור תמונת מצב',
    'sa.snapshot_created': 'תמונת מצב נוצרה בהצלחה!',
    'sa.snapshot_created_short': 'תמונת מצב נוצרה!',
    'sa.test_generated': 'נתוני בדיקה נוצרו בהצלחה!',
    'sa.no_snapshot': 'לא נמצאה תמונת מצב.',
    'sa.testing_tools': 'כלי בדיקה',
    'sa.testing_desc': 'פעולות ספציפיות להערכת לוגיקת שכבה 1.',
    'sa.run_calendar_test': 'הרצת יצירת בדיקות לוח שנה',
    'sa.run_teacher_gen': 'הרצת יצירת מורים',
    'sa.system_info': 'מידע מערכת',
    'sa.super_admin_label': 'מנהל-על',
    'sa.total_tenants': 'סה"כ ארגונים',
    'sa.total_access': 'סה"כ רשומות גישה',
    'sa.superadmin_badge': 'מנהל-על',
    'settings.english_us': 'English (United States)',
    'settings.tz_utc': 'UTC',
    'settings.tz_jerusalem': 'ירושלים (ישראל)',
    'settings.tz_eastern': 'זמן מזרחי (ארה"ב וקנדה)',
    'settings.tz_pacific': 'זמן מערבי (ארה"ב וקנדה)',
    'settings.date_mmddyyyy': 'MM/DD/YYYY (04/16/2026)',
    'settings.date_ddmmyyyy': 'DD/MM/YYYY (16/04/2026)',
    'settings.date_iso': 'YYYY-MM-DD (2026-04-16)',
    'settings.gcal_label': 'יומן גוגל',
    'settings.gcal_title': 'סנכרון יומן גוגל',
    'settings.gcal_reconnect': 'התחבר מחדש',
    'settings.gcal_auto_note': 'שיעורים חדשים יתווספו אוטומטית ליומן זה.',
    'power.time_range': 'טווח זמנים',
    'power.criteria': 'קריטריונים',
    'power.interactive_selection': 'בחירה אינטראקטיבית',
    'power.selected_events': 'אירועים נבחרים:',
    'power.import_csv_title': 'ייבוא לוח זמנים מ-CSV',
    'power.import_csv_desc': 'ייבוא מרוכז של סמסטרים, חגים או תקופות חסימה.',
    'power.blackout_label': 'חסימה',
    'power.alert_deleted': 'נמחקו ${count} אירועים בהצלחה.',
    'power.alert_no_valid': 'לא נמצאו שורות תקפות. ודא שהתאריכים בפורמט YYYY-MM-DD או M/D/YYYY.',
    'power.alert_parse_fail': 'נכשל בניתוח קובץ CSV.',
    'power.alert_imported': 'יובאו ${n} בלוקי לוח זמנים בהצלחה.',
    'layout.logo_alt': 'לוגו קדנצה',
    'layout.sandbox_badge': 'ארגז חול',
    'layout.sign_out': 'התנתק',
    'layout.mobile_access_label': 'גישה מנייד',
    'analysis.chart_name_placeholder': 'לדוגמה: הכנסות פסנתר',
    'analysis.edit_tooltip': 'עריכה',
    'analysis.duplicate_tooltip': 'שכפול',
    'gantt.name_placeholder': 'לדוגמה: חופשת חורף',
    'gantt.auto_hide': 'אוטומטית',
    'gantt.hide_label': 'הסתר',
    'dashboard.report_desc': 'על פי הסינונים הנוכחיים, דוחות יישלחו למורים הבאים.',
    'dashboard.report_success': 'הדוחות נשלחו בהצלחה!',
    'lists.no_items_found': 'לא נמצאו פריטים',
    'lists.csv_no_unique': 'לא נמצאו פריטים ייחודיים חדשים ב-CSV. ודא שהשתמשת בפורמט התבנית.',
    'room.subtitle': 'הגדר חללים ומסלולי ציוד.',
    'room.name_placeholder': 'לדוגמה: סטודיו A',
    'teach.alert_error_reading': 'שגיאה בקריאת הקובץ',
    'teach.alert_no_valid': 'לא נמצאו מורים תקפים או ייחודיים חדשים ב-CSV.\nודא שהקובץ מכיל עמודות: שם, דוא"ל, טלפון, תפקיד, קטגוריה, סוג תעריף, ערך תעריף, תגיות',
    'cal.alert_end_after_start': 'שעת הסיום חייבת להיות אחרי שעת ההתחלה',
    'power.title': 'כלים מתקדמים',
    'power.subtitle': 'פעולות מרוכזות לניהול אירועים.',
    'power.tab_filter': 'לפי מסנן',
    'power.tab_manual': 'בחירה ידנית',
    'power.tab_import': 'ייבוא לוח זמנים',
    'power.label_from': 'מ-',
    'power.label_to': 'עד',
    'power.select_time_range_first': 'אנא בחר טווח זמנים תחילה.',
    'power.clear_filters': 'נקה מסננים',
    'power.manual_desc': 'לחץ וגרור ישירות על רשת הלוח שנה כדי לצייר מלבן בחירה, או לחץ על אירועים בודדים כדי להחליף אותם.',
    'power.clear_selection': 'נקה בחירה',
    'power.download_template': 'הורד תבנית CSV',
    'power.processing': 'מעבד...',
    'power.drop_csv': 'גרור קובץ CSV או לחץ לעיון',
    'power.preview': 'תצוגה מקדימה',
    'power.items': 'פריטים',
    'power.confirm_import': 'אישור ייבוא',
    'power.targeted': 'ממוקדים',
    'power.adjust_filters': 'התאם מסננים.',
    'power.select_events': 'בחר אירועים.',
    'power.bulk_cancel': 'ביטול מרוכז',
    'power.bulk_delete': 'מחיקה מרוכזת',
    'power.confirm_action': 'האם אתה בטוח שברצונך',
    'power.action_cancel': 'לבטל',
    'power.action_delete': 'למחוק לצמיתות',
    'power.events_word': 'אירועים',
    'power.matching': 'תואמים',
    'power.selected_word': 'נבחרים',
    'power.alert_canceled': 'בוטלו בהצלחה',
    'power.alert_cancel_note': 'הערה: אירועים מבוטלים עשויים להיות מוסתרים. הפעל את מסנן "הצג מבוטלים" בסרגל הלוח שנה כדי לצפות בהם.',
    'fin.email_report': 'דוח אימייל',
    'fin.no_data_matches': 'אין נתונים התואמים למסננים הנוכחיים.',
    'fin.send_reports_title': 'שליחת דוחות פיננסיים',
    'fin.email_dispatched': 'דוחות אימייל נוצרו ונשלחו אל',
    'fin.recipients': 'נמענים',
    'fin.month_singular': 'חודש',
    'fin.months_plural': 'חודשים',
    'builder.viz_bar': 'עמודות',
    'builder.viz_stacked': 'מוערם',
    'builder.viz_line': 'קו',
    'builder.viz_pie': 'עוגה',
    'builder.viz_table': 'טבלה',
    'builder.agg_sum': 'סכום',
    'builder.agg_average': 'ממוצע',
    'builder.agg_count': 'ספירה',
    'builder.agg_min': 'מינימום',
    'builder.agg_max': 'מקסימום',
    'builder.tf_today': 'היום',
    'builder.tf_current_week': 'שבוע נוכחי',
    'builder.tf_current_month': 'חודש נוכחי',
    'builder.tf_custom_range': 'טווח מותאם',
    'builder.tf_specific_day': 'יום ספציפי',
    'builder.tf_specific_week': 'שבוע ספציפי',
    'builder.tf_specific_month': 'חודש ספציפי',
    'dim.teacher': 'מורה',
    'dim.position': 'תפקיד',
    'dim.category': 'קטגוריה',
    'dim.tag': 'תגית',
    'dim.rate_type': 'סוג תעריף',
    'dim.month': 'חודש',
    'dim.week': 'שבוע',
    'dim.day_of_week': 'יום בשבוע',
    'dim.room': 'חדר',
    'dim.classification': 'סיווג',
    'metric.active_hours': 'שעות פעילות',
    'metric.canceled_hours': 'שעות מבוטלות',
    'metric.total_hours': 'סה"כ שעות',
    'metric.hourly_cost': 'עלות שעתית',
    'metric.global_cost': 'עלות גלובלית',
    'metric.total_cost': 'עלות כוללת',
    'metric.event_count': 'מספר אירועים',
    'metric.teacher_count': 'מספר מורים',
    'metric.avg_rate': 'תעריף ממוצע',
    'super.add_btn': 'הוסף',
    'super.switch_bulk': 'עבור לקלט CSV מרוכז',
    'super.switch_single': 'עבור לקלט בודד',
    'super.role_viewer': 'צופה',
    'super.role_admin': 'מנהל',
    'super.tools_notice': 'כלים אלה זמינים אך ורק למנהל-על. אף מנהל דייר לא יכול לגשת אליהם.',
    'super.wipe_data': 'מחיקת נתונים',
    'settings.connect_account': 'חבר את החשבון שלי',
    'fin.rate_hourly': 'שעתי',
    'fin.rate_global': 'חודשי גלובלי',
    'app.something_wrong': 'משהו השתבש.',
    'app.collapse_sidebar': 'כווץ סרגל צד',
    'app.not_found': 'לא נמצא',
    'app.confirm_wipe': 'האם אתה בטוח שברצונך למחוק לצמיתות את כל המורים, החדרים, האירועים ונתוני גנט? לא ניתן לבטל פעולה זו.',
    'app.reload': 'טען מחדש',
    'sa.restore': 'שחזר',
    'cal.confirm_delete_event': 'האם אתה בטוח שברצונך למחוק אירוע זה?',
    'cal.confirm_delete_gantt': 'למחוק בלוק גנט זה? זה עלול להשפיע על תקופות חסימה.',
    'cal.occurrences': 'מופעים',
    'chart.no_data_filters': 'אין נתונים התואמים למסננים הנוכחיים',
    'builder.filters_applied': 'מסננים מופעלים',
    'builder.narrow_desc': 'צמצם נתוני תרשים לפי מורים, תפקידים, תגיות או קטגוריות',
    'gantt.confirm_delete_block': 'למחוק בלוק זה? אם מדובר בחסימה, האירועים ישוחזרו.',
    'lists.confirm_remove': 'מרשימות? רשומות קיימות המשתמשות בזה לא יעודכנו.',
    'lists.remove_word': 'הסר',
    'rooms.confirm_delete': 'האם אתה בטוח? אירועים מתוזמנים יסומנו עם אזהרות.',
    'teachers.confirm_delete': 'האם אתה בטוח שברצונך למחוק מורה זה? אירועים משויכים יציגו אזהרות.',
    'teachers.confirm_bulk_delete': 'מורים? לא ניתן לבטל פעולה זו.',
    'teachers.confirm_bulk_prefix': 'האם אתה בטוח שברצונך למחוק',
    'super.confirm_delete_org': 'האם אתה בטוח שברצונך למחוק את הארגון כולו',
    'super.delete_org_warn': 'פעולה זו לא תמחק נתוני Firestore, רק את רשומת המנהל.',
    'super.confirm_change_slug': 'אזהרה: שינוי מזהה הדייר יעביר את כל נתוני Firestore. להמשיך?',
    'super.confirm_revoke': 'האם אתה בטוח שברצונך לבטל גישה עבור',
    'super.id_label': 'מזהה:',
    'super.csv_format': 'אימייל, מזהה_ארגון, תפקיד',
    'super.confirm_snapshot': 'האם תרצה ליצור תמונת מצב לפני יצירת נתוני בדיקה?',
    'super.confirm_generate': 'ליצור נתוני בדיקה? פעולה זו תדרוס את הנתונים הנוכחיים.',
    'super.confirm_restore': 'לשחזר תמונת מצב? השינויים הנוכחיים יידרסו!',
    'super.confirm_cal_test': 'להריץ מחולל בדיקות לוח שנה? המצב הנוכחי יימחק. (תמונת מצב נלקחת אוטומטית)',
    'super.confirm_teacher_test': 'להריץ מחולל מורים? המורים הנוכחיים יוחלפו. (תמונת מצב נלקחת אוטומטית)',
    'settings.currency_ils': '₪ — שקל חדש (ILS)',
    'settings.currency_usd': '$ — דולר אמריקאי (USD)',
    'settings.currency_eur': '€ — אירו (EUR)',
    'settings.currency_gbp': '£ — לירה שטרלינג (GBP)',
    'settings.currency_jpy': '¥ — ין יפני (JPY)',
    'settings.currency_inr': '₹ — רופי הודי (INR)',
    'settings.currency_btc': '₿ — ביטקוין (BTC)',
    'settings.time_12h': '12 שעות (1:00 PM)',
    'settings.time_24h': '24 שעות (13:00)',
    'settings.choose_calendar': '-- בחר לוח שנה --',
    'settings.hebrew_lang': 'עברית (Hebrew)',
    'settings.diff_account': 'חשבון אחר — סנכרון לא פעיל עבורך',
    'settings.sync_note': 'אירועים יסונכרנו ללוח שנה של Google רק כשהמנהל המיועד מחובר. רק חשבון זה יכול לשנות את הגדרות הלוח שנה.',
    'fin.header_teacher': 'מורה',
    'fin.header_position': 'תפקיד',
    'fin.header_rate_type': 'סוג תעריף',
    'fin.header_rate': 'תעריף',
    'fin.header_active_hrs': 'שעות פעילות',
    'fin.header_canceled_hrs': 'שעות מבוטלות',
    'fin.header_hourly_cost': 'עלות שעתית',
    'fin.header_oneoff': 'תשלומים חד-פעמיים',
    'fin.header_global_cost': 'עלות גלובלית',
    'fin.header_total_cost': 'עלות כוללת',
    'fin.per_hr': '/שעה',
    'fin.per_mo': '/חודש',
    'nav.gantt.subtitle': 'ניהול סמסטרים וחסימות.',
    'gantt.blackout_label': 'חסימה',
    'gantt.no_periods': 'לא הוגדרו תקופות.',
    'gantt.edit_period': 'עריכת תקופה',
    'gantt.add_period': 'הוספת תקופת גנט / חסימה',
    'gantt.blackout_warning': 'זהירות: אירועים קיימים בטווח זה יוסתרו.',
    'gantt.save_changes': 'שמור שינויים',
    'gantt.create_apply': 'צור והחל',
    'recurrence.on_day_of_month': 'ב-{ordinal} בכל חודש',
    'recurrence.on_pos_day_of_month': 'ביום {dayName} ה{pos} בכל חודש',
    'recurrence.ordinal_st': '',
    'recurrence.ordinal_nd': '',
    'recurrence.ordinal_rd': '',
    'recurrence.ordinal_th': '',
    'recurrence.pos_1st': 'ראשון',
    'recurrence.pos_2nd': 'שני',
    'recurrence.pos_3rd': 'שלישי',
    'recurrence.pos_4th': 'רביעי',
    'recurrence.pos_5th': 'חמישי',
    'recurrence.day_sunday': 'ראשון',
    'recurrence.day_monday': 'שני',
    'recurrence.day_tuesday': 'שלישי',
    'recurrence.day_wednesday': 'רביעי',
    'recurrence.day_thursday': 'חמישי',
    'recurrence.day_friday': 'שישי',
    'recurrence.day_saturday': 'שבת',
    'recurrence.after': 'אחרי',
    'recurrence.edit_series_title': 'עריכת אירוע חוזר',
    'recurrence.delete_series_title': 'מחיקת אירוע חוזר',
    'recurrence.restore_series_title': 'שחזור אירוע חוזר',
    'recurrence.cancel_series_title': 'ביטול אירוע חוזר',
    'recurrence.series_desc_edit': 'זהו חלק מסדרה חוזרת. מה ברצונך לערוך?',
    'recurrence.series_desc_delete': 'זהו חלק מסדרה חוזרת. מה ברצונך למחוק?',
    'recurrence.series_desc_restore': 'זהו חלק מסדרה חוזרת. מה ברצונך לשחזר?',
    'recurrence.series_desc_cancel': 'זהו חלק מסדרה חוזרת. מה ברצונך לבטל?',
    'recurrence.just_this_one': 'רק את זה',
    'recurrence.all_events': 'כל האירועים',
    'room.itinerary_equipment': 'ציוד ומלאי',
    'room.empty_state': 'לא הוגדרו חדרים. הוסף חדר כדי להתחיל.',
    'lists.add_placeholder': 'הוסף {title}...',
    'lists.found_items': 'נמצאו {count} פריטים ייחודיים חדשים.',
    'teach.err_no_position': 'נא להוסיף לפחות תפקיד אחד עם שם.',
    'teach.err_color_taken': 'צבע זה כבר מוקצה למורה אחר. אנא בחר צבע ייחודי.',
    'teach.found_prefix': 'נמצאו',
    'builder.active_badge': 'פעיל',
    'builder.data_filters_desc': 'צמצם נתוני תרשים לפי מורים, תפקידים, תגיות או קטגוריות ספציפיות',
    'builder.preview_summary': '{events} אירועים · {dim} × {metrics} מדד(ים) → {viz}',
    'builder.n_events': '({count} אירועים)',
    'builder.primary_label': 'ראשי',
    'builder.footer_summary': '{dim} × {metrics} מדד(ים) → {viz}',
    'builder.footer_filters': ' · {count} סינון(ים)',
  }
};

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'T1', fullName: 'John Smith',
    positions: ['Piano Instructor'],
    positionAssignments: [
      { id: 'T1_PA0', positionName: 'Piano Instructor', category: 'Individual Lesson', rateType: 'HOURLY', rateValue: 150 },
    ],
    tags: ['Piano Dept', 'Senior Staff'], phone: '555-0101', email: 'john@music.com', color: '#3b82f6'
  },
  {
    id: 'T2', fullName: 'Sarah Jones',
    positions: ['Voice Coach', 'Choir Director'],
    positionAssignments: [
      { id: 'T2_PA0', positionName: 'Voice Coach', category: 'Individual Lesson', rateType: 'HOURLY', rateValue: 120 },
      { id: 'T2_PA1', positionName: 'Choir Director', category: 'Group Lesson', rateType: 'GLOBAL_MONTHLY', rateValue: 5000 },
    ],
    tags: ['Vocal Dept'], phone: '555-0102', email: 'sarah@music.com', color: '#ef4444'
  },
  {
    id: 'T3', fullName: 'Michael Brown',
    positions: ['Violin Teacher'],
    positionAssignments: [
      { id: 'T3_PA0', positionName: 'Violin Teacher', category: 'Individual Lesson', rateType: 'HOURLY', rateValue: 130 },
    ],
    tags: ['Strings Dept'], phone: '555-0103', email: 'mike@music.com', color: '#10b981'
  },
];

export const INITIAL_ROOMS: Room[] = [
  { id: 'R1', name: 'Studio A', itinerary: 'Grand Piano, roughly 20 person capacity.' },
  { id: 'R2', name: 'Studio B', itinerary: 'Upright Piano, soundproofed.' },
  { id: 'R3', name: 'Practice Room 1', itinerary: 'Small room for individual practice.' },
];

export const INITIAL_RATE_CARDS: RateCard[] = [
  {
    id: 'RC_DEFAULT',
    versionId: 'V1',
    entries: [
      { id: 'RC_DEFAULT_E1', categoryId: 'individual_lesson', effectiveFrom: '2020-01-01', rateType: 'HOURLY', rateValue: 150 },
      { id: 'RC_DEFAULT_E2', categoryId: 'group_lesson', effectiveFrom: '2020-01-01', rateType: 'GLOBAL_MONTHLY', rateValue: 5000 },
      { id: 'RC_DEFAULT_E3', categoryId: 'rehearsal', effectiveFrom: '2020-01-01', rateType: 'HOURLY', rateValue: 100 },
    ]
  }
];

// Helper to generate some initial events relative to "today"
const today = new Date();
const getIso = (daysOffset: number, hour: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: 'E1',
    name: 'Piano Lesson - Alice',
    description: 'Weekly lesson',
    teacherId: 'T1',
    roomId: 'R1',
    positionId: 'T1_PA0',
    classification: Classification.INDIVIDUAL,
    start: getIso(0, 10),
    end: getIso(0, 11),
    isCanceled: false,
    isHidden: false,
  },
  {
    id: 'E2',
    name: 'Voice Coaching - Bob',
    description: 'Prep for recital',
    teacherId: 'T2',
    roomId: 'R2',
    positionId: 'T2_PA0',
    classification: Classification.INDIVIDUAL,
    start: getIso(0, 10), // INTENTIONAL CONFLICT with time, different room
    end: getIso(0, 11),
    isCanceled: false,
    isHidden: false,
  },
  {
    id: 'E3',
    name: 'Group Theory',
    description: 'Beginner theory',
    teacherId: 'T1', // INTENTIONAL CONFLICT: T1 is also in E1 at this time
    roomId: 'R3',
    positionId: 'T1_PA0',
    classification: Classification.GROUP,
    start: getIso(0, 10),
    end: getIso(0, 11),
    isCanceled: false,
    isHidden: false,
  }
];

export const INITIAL_GANTT: GanttBlock[] = [
  {
    id: 'G1',
    title: 'Winter Semester',
    startDate: new Date(today.getFullYear(), 0, 1).toISOString(),
    endDate: new Date(today.getFullYear(), 3, 30).toISOString(),
    color: '#3b82f6',
    isBlackout: false,
  }
];

export const generateId = () => Math.random().toString(36).substr(2, 9);

export const formatDateForInput = (isoString: string) => {
  if (!isoString) return '';
  const date = new Date(isoString);
  const offset = date.getTimezoneOffset();
  const localDate = new Date(date.getTime() - (offset * 60 * 1000));
  return localDate.toISOString().slice(0, 16);
};

export const formatDate = (date: Date, format: string) => {
  const d = date.getDate().toString().padStart(2, '0');
  const m = (date.getMonth() + 1).toString().padStart(2, '0');
  const y = date.getFullYear();

  switch (format) {
    case 'DD/MM/YYYY': return `${d}/${m}/${y}`;
    case 'YYYY-MM-DD': return `${y}-${m}-${d}`;
    default: return `${m}/${d}/${y}`; // MM/DD/YYYY
  }
};
