import { Teacher, Room, CalendarEvent, GanttBlock, Classification, AppSettings, ListsState, PositionAssignment, RateCard } from './types';

export const COLORS = [
  '#3b82f6', // blue
  '#ef4444', // red
  '#10b981', // green
  '#f59e0b', // amber
  '#8b5cf6', // violet
  '#ec4899', // pink
  '#6366f1', // indigo
  '#14b8a6', // teal
  '#f97316', // orange
  '#64748b', // slate
];

// --- Migration helper: ensure old teacher data gets positionAssignments ---
export const migrateTeacher = (t: any): Teacher => {
  // If positionAssignments already exists and has data, just ensure positions is synced
  if (t.positionAssignments && t.positionAssignments.length > 0) {
    return {
      ...t,
      tags: t.tags || [],
      positions: t.positionAssignments.map((pa: PositionAssignment) => pa.positionName),
    };
  }

  // Legacy migration: create positionAssignments from old positions[] array
  const assignments: PositionAssignment[] = (t.positions || []).map((posName: string, idx: number) => ({
    id: `${t.id}_PA${idx}`,
    positionName: posName,
    category: 'Individual Lesson',  // Safe default
    rateType: 'HOURLY' as const,
    rateValue: 0,                   // Unknown until user sets it
  }));

  return {
    ...t,
    tags: t.tags || [],
    positionAssignments: assignments,
    positions: t.positions || [],
  };
};

export const INITIAL_SETTINGS: AppSettings = {
  language: 'en-US',
  dateFormat: 'DD/MM/YYYY',
  timeFormat: '12h',
  timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  defaultEventDuration: 60,
  weekNumberDisplay: 'none',
  currency: '₪',
  developerMode: false
};

export const INITIAL_LISTS: ListsState = {
  positions: ['Piano Instructor', 'Voice Coach', 'Violin Teacher', 'Choir Director', 'Theory Teacher'],
  tags: ['Piano Dept', 'Strings Dept', 'Vocal Dept', 'Senior Staff', 'Junior Staff'],
  classifications: Object.values(Classification) as string[]
};

export const HEBREW_CALENDAR_OPTIONS = {
  // Config for Hebcal if needed
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    'app.title': 'Music Center Calendar',
    'app.subtitle': 'Management System',
    'nav.calendar': 'Smart Calendar',
    'nav.gantt': 'Gantt & Blackout',
    'nav.teachers': 'Teachers',
    'nav.rooms': 'Rooms',
    'nav.lists': 'Manage Lists',
    'nav.manage': 'Manage',
    'nav.financial': 'Financial Dashboard',
    'nav.settings': 'Settings',
    'nav.power_tools': 'Power Tools',
    'nav.analysis': 'Financial Analysis',
    'nav.super_admin': 'Super Admin',
    'nav.mobile_access': 'Mobile Access',
    'ops': 'Operations',
    'admin': 'Administration',
    'analytics': 'Analytics',
    'today': 'TODAY',
    // Buttons
    'btn.add': 'Add',
    'btn.create': 'Create',
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.delete': 'Delete',
    'btn.close': 'Close',
    'btn.confirm': 'Confirm',
    'btn.back': 'Back',
    'btn.export': 'Export',
    'btn.import': 'Import',
    'btn.clear_all': 'Clear All',
    'btn.sign_out': 'Sign Out',
    'btn.connect_account': 'Connect My Account',
    'btn.disconnect': 'Disconnect',
    'btn.reconnect': 'Reconnect',
    'btn.save_insight': 'Save Insight',
    'btn.download_report': 'Download Report (CSV)',
    // Calendar view
    'mode.day': 'DAY',
    'mode.week': 'WEEK',
    'mode.month': 'MONTH',
    'mode.list': 'LIST',
    'filter.teacher': 'Teacher: All',
    'filter.room': 'Room: All',
    'filter.type': 'Type: All',
    'filter.category_all': 'Category: All',
    'filter.no_filters': 'No Filters',
    'filter.show_canceled': 'Show Canceled',
    'filter.show_blackouts': 'Show Blackouts',
    'filter.all_teachers': 'All Teachers',
    'filter.all_categories': 'All Categories',
    'filter.all_types': 'All Types',
    'filter.all_tags': 'All Tags',
    'filter.by_position': 'Filter by Position',
    'filter.by_tag': 'Filter by Tag',
    // Event modal
    'modal.add_event': 'Add Event',
    'modal.edit_event': 'Edit Event',
    'label.name': 'Event Name',
    'label.desc': 'Description',
    'label.teacher': 'Teacher',
    'label.room': 'Room',
    'label.type': 'Type',
    'label.start': 'Start',
    'label.end': 'End',
    'label.date': 'Date',
    'label.position': 'Position',
    'label.recurrence': 'Recurrence',
    'label.full_name': 'Full Name',
    'label.teacher_color': 'Teacher Color',
    'label.category': 'Category',
    'label.rate_type': 'Rate Type',
    'label.room_name': 'Room Name',
    'label.itinerary_desc': 'Itinerary / Description',
    'label.from': 'From',
    'label.to': 'To',
    'label.optional': '(Optional)',
    'label.requires_teacher': '(Requires Teacher & Position)',
    'label.live': 'Live',
    'label.no_room': 'No Room',
    'label.no_room_dash': '— No Room —',
    // Calendar states
    'cal.canceled': 'CANCELED',
    'cal.no_events': 'No events',
    'cal.hide_canceled': 'Hide Canceled',
    'cal.hide_blackouts': 'Hide Blackouts',
    'cal.recurring_event': 'Recurring Event',
    'cal.every': 'Every',
    'cal.on_days': 'On days',
    'cal.monthly_mode': 'Monthly mode',
    'cal.mark_canceled': 'Mark as Canceled',
    'cal.cancel_pay_status': 'Cancellation Pay Status',
    'cal.no_pay': 'No Pay',
    'cal.paid_cancel': 'Paid Cancellation',
    'cal.delete_event': 'Delete Event',
    'cal.payment_method': 'Payment Method',
    'cal.select_category': 'Select Category',
    'cal.save_changes': 'Save Changes',
    'cal.save_update_series': 'Save & Update Series',
    'cal.update_this_only': 'Update This Only',
    'cal.update_all_future': 'Update All Future',
    'cal.recurring_series_msg': 'This is part of a recurring series. What would you like to',
    'cal.this_event_only': 'This event only',
    'cal.this_and_future': 'This and all future events',
    'cal.all_in_series': 'All events in series',
    // Calendar recurrence
    'recurrence.none': 'Does not repeat',
    'recurrence.daily': 'Daily',
    'recurrence.weekly': 'Weekly',
    'recurrence.biweekly': 'Bi-Weekly',
    'recurrence.monthly': 'Monthly',
    'recurrence.yearly': 'Yearly',
    'recurrence.until': 'Until',
    'recurrence.ends_after': 'Ends after',
    'recurrence.ends_on': 'Ends on',
    'recurrence.occurrences': 'occurrences',
    // Settings
    'settings.general': 'General Settings',
    'settings.integrations': 'Integrations',
    'settings.dev_tools': 'Developer Tools',
    'settings.generate_data': 'Generate Test Data',
    'settings.generate_data_desc': 'Populate the calendar with 20 teachers and random events.',
    'settings.generate_btn': 'Generate Data',
    'settings.unsaved': 'You have unsaved changes',
    'settings.testing_tools': 'Testing Tools',
    'settings.currency': 'Currency',
    'settings.currency_symbol': 'Currency Symbol',
    'settings.currency_desc': 'This symbol will appear next to all cost values in the financial dashboard, analysis, and exports.',
    'settings.gcal_sync': 'Google Calendar Sync',
    'settings.gcal_desc': 'Push scheduled lessons to the tenant admin\'s Google Calendar.',
    'settings.connected_via': 'Connected via',
    'settings.sync_inactive': 'Different account — sync inactive for you',
    'settings.token_expired': 'Authentication token expired. Please reconnect to restore sync.',
    'settings.fetching_cals': 'Fetching your calendars...',
    'settings.select_calendar': 'Select Target Calendar',
    'settings.choose_cal': '-- Choose a calendar --',
    'settings.primary': '(Primary)',
    'settings.auto_add_desc': 'New lessons will be automatically added to this calendar.',
    'settings.sync_managed_by': 'Calendar sync is managed by {email}',
    'settings.sync_condition': 'Events will only sync to Google Calendar when the designated admin ({email}) is logged in.',
    'settings.admin_only': 'Admin only',
    'settings.managed_by_admin': 'Managed by tenant admin',
    'settings.week_hidden': 'Hidden',
    'settings.week_number': 'Week Number',
    'settings.week_of': 'Week of...',
    // Labels
    'label.default_lang': 'Default Language',
    'label.system_default': 'System Default',
    'label.coming_soon': 'Coming Soon',
    'label.timezone': 'Time Zone',
    'label.date_format': 'Date Format',
    'label.time_format': 'Time Format',
    'label.calendar_defaults': 'Calendar Defaults',
    'label.default_duration': 'Default Event Duration (minutes)',
    'label.week_numbers': 'Week Number Display',
    'label.blackout': 'BLACKOUT',
    // Nav sections
    'nav.section.localization': 'Localization',
    'nav.section.date_time': 'Date & Time',
    'nav.section.analytics': 'Analytics',
    'nav.section.operations': 'Operations',
    'nav.section.admin': 'Administration',
    // Roles
    'role.admin': 'Admin',
    'role.viewer': 'Viewer',
    // Alerts
    'alert.confirm_generate': 'This will overwrite existing teachers and events. Continue?',
    'alert.data_generated': 'Test data generated!',
    'alert.delete_event': 'Are you sure you want to delete this event?',
    'alert.delete_gantt': 'Delete this Gantt block? This may affect blackouts.',
    'alert.end_time_error': 'End time must be after start time',
    'alert.delete_teacher': 'Are you sure you want to delete this teacher? Associated events will show warnings.',
    'alert.delete_room': 'Are you sure? Scheduled events will flag warnings.',
    'alert.delete_gantt_block': 'Delete this block? If it is a blackout, events will be restored.',
    'alert.error_reading_file': 'Error reading file',
    'alert.no_valid_teachers': 'No valid or new unique teachers found in CSV.',
    'alert.no_valid_rows': 'No valid rows found. Please ensure dates are in YYYY-MM-DD or DD/MM/YYYY format.',
    'alert.csv_parse_fail': 'Failed to parse CSV file.',
    'alert.delete_all_data': 'Are you sure you want to permanently delete all Teachers, Rooms, Events, and Gantt Blocks from THIS workspace in the cloud?',
    'alert.action_cannot_undo': 'This action cannot be undone.',
    // Power Tools
    'pt.bulk_delete': 'Bulk Delete',
    'pt.date_range': 'Date Range',
    'pt.criteria': 'Filter Criteria',
    'pt.preview': 'Preview',
    'pt.delete_all': 'Delete All Matches',
    'pt.confirm_delete': 'Please confirm deletion of {count} events.',
    'pt.success': 'Successfully deleted {count} events.',
    'pt.no_matches': 'No matching events found.',
    'pt.time_range': 'Time Range',
    'pt.interactive': 'Interactive Selection',
    'pt.import_csv': 'Import Schedule from CSV',
    // Financial Dashboard
    'fin.title': 'Financial Dashboard',
    'fin.all_time': 'All Time',
    'fin.grand_total': 'Grand Total',
    'fin.hourly_fees': 'Hourly Fees',
    'fin.global_monthly': 'Global Monthly',
    'fin.active_hours': 'Active Hours',
    'fin.canceled': 'Canceled',
    'fin.teacher_metrics': 'Teacher Metrics',
    'fin.sort_hint': '· Click headers to sort',
    'fin.current_week': 'Current Week',
    'fin.daily': 'Daily',
    'fin.hourly': 'Hourly',
    'fin.weekly': 'Weekly',
    'fin.monthly': 'Monthly',
    'fin.revenue_trend': 'Revenue Trend',
    // Table headers
    'col.name': 'Name',
    'col.active_hrs': 'Active Hrs',
    'col.canceled_hrs': 'Canceled Hrs',
    'col.cancel_count': 'Cancel #',
    'col.hourly_cost': 'Hourly Cost',
    'col.one_off_cost': 'One-Off Cost',
    'col.global_cost': 'Global Cost',
    'col.total': 'Total',
    'col.recipient': 'Recipient',
    'col.email_address': 'Email Address',
    'col.total_payout': 'Total Payout',
    'col.positions_rates': 'Positions & Rates',
    'col.contact': 'Contact',
    'col.rates': 'Rates',
    'col.entry_name': 'Entry Name',
    'col.actions': 'Actions',
    // Financial Analysis
    'fin_ana.title': 'Financial Analysis',
    'fin_ana.delete_chart': 'Delete Chart',
    'fin_ana.insight_title': 'Insight Title',
    'fin_ana.metric': 'Metric',
    'fin_ana.total_active_hours': 'Total Active Hours',
    'fin_ana.total_canceled_hours': 'Total Canceled Hours',
    'fin_ana.hourly_payroll': 'Hourly Payroll',
    'fin_ana.global_payroll': 'Global Payroll',
    'fin_ana.grand_total_payroll': 'Grand Total Payroll',
    'fin_ana.avg_hours_teacher': 'Avg Hours per Teacher',
    'fin_ana.avg_payroll_teacher': 'Avg Payroll per Teacher',
    'fin_ana.cancel_rate': 'Cancellation Rate',
    'fin_ana.highest_earner': 'Highest Earner',
    'fin_ana.lowest_earner': 'Lowest Earner',
    'fin_ana.choose_insights': 'Choose Visible Insights',
    'fin_ana.no_insights': 'No insights selected. Click Edit to choose which insights to display.',
    'fin_ana.create_first_chart': 'Create your first custom chart',
    'fin_ana.back_to_dashboard': 'Back to Dashboard',
    'fin_ana.classify_desc': 'Classify data by category (timeframes are controlled separately below)',
    'fin_ana.select_period_desc': 'Select the time period for analysis (independent of grouping)',
    // Teacher Manager
    'teach.title': 'Teacher Management',
    'teach.add': 'Add Teacher',
    'teach.import_title': 'Import Teachers',
    'teach.import_csv': 'Import Teachers from CSV',
    'teach.csv_columns': 'Select your .csv file with columns: Name, Email, Phone, Tags',
    'teach.colors_auto': '* Colors will be auto-assigned',
    'teach.add_first_position': '+ Add first position',
    'teach.position_assignment': 'Position Assignment',
    'teach.select_to_import': 'Select Teachers to Import',
    'teach.unique_teachers': 'unique teachers. Select the ones you want to import.',
    'teach.selected': 'Selected',
    'teach.already_in_list': 'Already in list',
    'teach.skip': 'Skip',
    'teach.no_teachers_found': 'No teachers found in this file.',
    'teach.back_to_list': 'Back to List',
    // Room Manager
    'room.title': 'Room Management',
    'room.itinerary': 'Itinerary & Equipment',
    // Gantt
    'gantt.title': 'Semesters & Blackouts',
    'gantt.subtitle': 'Manage semesters & blackouts.',
    'gantt.label_title': 'Title',
    'gantt.start_date': 'Start Date',
    'gantt.end_date': 'End Date',
    'gantt.display_color': 'Display Color',
    'gantt.apply_blackout': 'Apply Blackout',
    'gantt.blackout_desc': 'Automatically HIDE all events in this range from calendar and reports.',
    // Chart Builder
    'chart.title_label': 'Chart Title',
    'chart.filter_mode': 'Filter Mode',
    'chart.live': 'Live',
    'chart.live_desc': 'Reacts to dashboard filters',
    'chart.snapshot': 'Snapshot',
    'chart.snapshot_desc': 'Freezes filters at save time',
    'chart.sort_by': 'Sort By',
    'chart.dimension_label': 'Dimension Label',
    'chart.ascending': 'Ascending',
    'chart.descending': 'Descending',
    'chart.no_options': 'No options available',
    'chart.add_position': 'Add Position',
    'chart.position_name': 'Position Name',
    'chart.select_icon': 'Select Icon',
    'chart.choose_icon': 'Choose an icon for this position',
    // Filter sections
    'filter.teachers': 'Teachers',
    'filter.positions': 'Positions',
    'filter.tags': 'Tags',
    'filter.categories': 'Categories',
    'filter.rate_type': 'Rate Type',
    // Manage Lists
    'lists.title': 'Dropdown Lists',
    'lists.desc': 'Update your app by modifying these lists.',
    'lists.classifications': 'Classifications',
    'lists.how_to': 'How to use this tool:',
    'lists.step1': '1. Fill in the data below',
    'lists.step2': '2. Export to CSV',
    'lists.step3': '3. Open in your app',
    'lists.add_row': 'Add Row',
    'lists.template': 'Template',
    // Auth
    'auth.sign_in_google': 'Sign In with Google',
    'auth.workspaces': 'Authorized Workspaces',
    'auth.no_workspaces': 'No authorized workspaces found.',
    'auth.signing_in': 'Syncing with Cadenza Cloud...',
    // Tooltips
    'tooltip.edit': 'Edit',
    'tooltip.duplicate': 'Duplicate',
    'tooltip.delete': 'Delete',
    'tooltip.switch_light': 'Switch to Light Mode',
    'tooltip.switch_dark': 'Switch to Dark Mode',
    'tooltip.expand_sidebar': 'Expand Sidebar',
    'tooltip.collapse_sidebar': 'Collapse Sidebar',
    'tooltip.open_menu': 'Open Menu',
    'tooltip.add_event': 'Click to add event',
    'tooltip.toggle_filters': 'Toggle Filters',
    'tooltip.remove_position': 'Remove position',
    // Placeholders
    'placeholder.search_teachers': 'Search teachers...',
    'placeholder.or_type_new': 'Or type new...',
    'placeholder.event_name': 'e.g. Piano Lesson',
    'placeholder.room_details': 'Details about equipment, capacity, etc.',
    'placeholder.choose_calendar': '-- Choose a calendar --',
    // Dynamic
    'dynamic.rate_hourly': 'Rate ({currency}/hour)',
    'dynamic.monthly_fee': 'Monthly Fee ({currency})',
    'dynamic.send_reports': 'Send {n} Reports',
    'dynamic.week_of': 'Week of {date}',
    'dynamic.hourly_currency': 'Hourly ({currency})',
    'dynamic.one_off_currency': 'One-Off ({currency})',
    'dynamic.global_currency': 'Global ({currency})',
    'dynamic.total_currency': 'Total ({currency})',
    'dynamic.one_off_price': 'One-Off Price ({currency})',
    // Footer
    'footer.copyright': '© 2026 Music Center',
    // Super Admin
    'super.title': 'Super Admin',
    'super.delete_all': 'Delete All Data',
      'analysis.title': 'Financial Analysis',
    'analysis.subtitle': 'Insights, charts, comparisons, and deep data exploration.',
    'analysis.key_insights': 'Key Insights',
    'analysis.charts': 'Charts',
    'analysis.new_chart': 'New Chart',
    'analysis.create_first_chart': 'Create your first custom chart',
    'analysis.create_first_chart_desc': 'Group data by any dimension, pick metrics, and choose a visualization',
    'analysis.advanced_filters': 'Advanced Filters',
    'analysis.clear_all': 'Clear all',
    'analysis.choose_insights': 'Choose Visible Insights',
    'analysis.custom_insight': 'Custom Insight',
    'analysis.show_all': 'Show All',
    'analysis.no_insights': 'No insights selected.',
    'analysis.click_edit': 'Click Edit to choose which insights to display.',
    'analysis.filters': 'Filters',
    'analysis.back_to_dashboard': 'Back to Dashboard',
    'analysis.open_menu': 'Open Menu',
    'time.current_week': 'Current Week',
    'time.current_month': 'Current Month',
    'time.custom_range': 'Custom Range',
    'time.all_time': 'All Time',
    'time.today': 'Today',
    'time.specific_day': 'Specific Day',
    'time.specific_week': 'Specific Week',
    'time.specific_month': 'Specific Month',
    'insight.most_hours': 'Most Hours Taught',
    'insight.most_canceled': 'Most Canceled Hours',
    'insight.highest_payroll': 'Highest Payroll',
    'insight.lowest_payroll': 'Lowest Payroll',
    'insight.cancel_rate': 'Cancellation Rate',
    'insight.avg_cost': 'Avg Cost / Teacher',
    'insight.top_position': 'Top Position (Hrs)',
    'insight.cost_split': 'Hourly vs Global',
    'insight.most_positions': 'Most Positions',
    'insight.active_teachers': 'Active Teachers',
    'insight.of_active_hours': 'of all active hours',
    'insight.of_their_hours': 'of their total hours',
    'insight.no_cancellations': 'No cancellations',
    'insight.of_total_payroll': 'of total payroll',
    'insight.of_total': 'of total',
    'insight.no_data': 'No data',
    'insight.most_active_position': 'Most active position',
    'metric.total_active_hours': 'Total Active Hours',
    'metric.total_canceled_hours': 'Total Canceled Hours',
    'metric.hourly_payroll': 'Hourly Payroll',
    'metric.oneoff_payroll': 'One-Off Payroll',
    'metric.global_payroll': 'Global Payroll',
    'metric.grand_total': 'Grand Total Payroll',
    'metric.avg_hours': 'Avg Hours per Teacher',
    'metric.avg_payroll': 'Avg Payroll per Teacher',
    'metric.highest_earner': 'Highest Earner',
    'metric.lowest_earner': 'Lowest Earner',
    'metric.all_teachers': 'All Teachers',
    'modal.new_insight': 'New Insight',
    'modal.insight_title': 'Insight Title',
    'modal.metric': 'Metric',
    'modal.filter_by_teacher': 'Filter by Teacher (Optional)',
    'modal.save_insight': 'Save Insight',
    'modal.totals': 'Totals',
    'modal.averages_rates': 'Averages & Rates',
    'modal.extremes': 'Extremes',
    'modal.delete_chart': 'Delete Chart',
    'modal.cannot_undo': 'This action cannot be undone.',
    'modal.confirm_delete_chart': 'Are you sure you want to delete',
    'chart.updated': 'Updated',
    'chart.edit': 'Edit',
    'chart.duplicate': 'Duplicate',
    'chart.delete': 'Delete',
    'chart.done': 'Done',
    'filter.hourly': 'Hourly',
    'filter.global_monthly': 'Global Monthly',
    'builder.title': 'Chart Builder',
    'builder.edit_chart': 'Edit Chart',
    'builder.chart_title': 'Chart Title',
    'builder.dimension_label': 'Dimension Label',
    'builder.preview': 'Preview',
    'builder.save_chart': 'Save Chart',
    'cal.teacher': 'Teacher',
    'cal.room': 'Room',
    'cal.description': 'Description',
    'cal.event_name': 'Event Name',
    'cal.type': 'Type',
    'cal.start': 'Start',
    'cal.end': 'End',
    'cal.add_event': 'Add Event',
    'cal.edit_event': 'Edit Event',
    'cal.recurrence': 'Recurrence',
    'cal.no_repeat': 'Does not repeat',
    'cal.daily': 'Daily',
    'cal.weekly': 'Weekly',
    'cal.monthly': 'Monthly',
    'cal.yearly': 'Yearly',
    'lists.manage_title': 'Manage Lists',
    'lists.configure_desc': 'Configure global dropdown options for Positions, Tags, and Classifications.',
    'lists.positions': 'Positions',
    'lists.tags': 'Tags',
    'lists.import_preview': 'Import Preview',
    'lists.new_positions': 'New Positions',
    'lists.new_tags': 'New Tags',
    'lists.new_classifications': 'New Classifications',
    'lists.import_all': 'Import All',
    'lists.no_items': 'No items found',
    'lists.import_csv': 'Import CSV',
    'room.add': 'Add Room',
    'room.edit': 'Edit Room',
    'room.add_new': 'Add New Room',
    'room.itinerary_desc': 'Itinerary / Description',
    'room.no_rooms': 'No rooms configured. Add one to get started.',
    'room.no_details': 'No details provided.',
    'room.equipment': 'Equipment',
    'cal.today': 'TODAY',
    'cal.day': 'DAY',
    'cal.week': 'WEEK',
    'cal.month': 'MONTH',
    'cal.toggle_filters': 'Toggle Filters',
    'cal.week_of': 'Week of',
    'cal.week_num': 'Week',
    'cal.click_add': 'Click to add event',
    'cal.unnamed': 'Unnamed Event',
    'cal.blackout_period': 'BLACKOUT PERIOD',
    'cal.recurring': 'Recurring',
    'cal.part_of_series': 'Part of Series',
    'cal.filter.teacher_all': 'Teacher: All',
    'cal.filter.room_all': 'Room: All',
    'cal.filter.type_all': 'Type: All',
    'cal.filter.position_all': 'Position: All',
    'cal.filter.tag_all': 'Tag: All',
    'cal.detail.edit': 'Edit',
    'cal.detail.restore': 'Restore',
    'cal.detail.cancel_event': 'Cancel',
    'cal.detail.delete': 'Delete',
    'speed.power_tools': 'Power Tools',
    'speed.gantt_view': 'Gantt View',
    'speed.new_event': 'New Event',
    'event.new': 'New Event',
    'event.edit': 'Edit Event',
    'event.name': 'Event Name',
    'event.name_placeholder': 'e.g. Piano Lesson',
    'event.category': 'Category',
    'event.select_category': 'Select Category',
    'event.teacher_lessons': 'Teacher Lessons',
    'event.individual_lesson': 'Individual Lesson',
    'event.group_lesson': 'Group Lesson',
    'event.general_events': 'General Events',
    'event.teacher': 'Teacher',
    'event.optional': '(Optional)',
    'event.select_teacher': 'Select Teacher',
    'event.org_no_teacher': 'Organization / No Teacher (Optional)',
    'event.select_category_first': 'Select Category First',
    'event.position': 'Position',
    'event.select_teacher_first': 'Select Teacher First',
    'event.no_positions': 'No positions available for this teacher under this category',
    'event.select_position': 'Select a position',
    'event.payment_method': 'Payment Method',
    'event.no_payment': 'No Payment (Scheduling Only)',
    'event.use_position_rate': 'Use Position Rate',
    'event.requires_teacher_position': '(Requires Teacher & Position)',
    'event.one_off_payment': 'One-Off Payment',
    'event.one_off_price': 'One-Off Price',
    'event.room': 'Room',
    'event.no_room': 'No Room',
    'event.start_time': 'Start Time',
    'event.end_time': 'End Time',
    'event.description_label': 'Description',
    'recurrence.recurring_event': 'Recurring Event',
    'recurrence.every': 'Every',
    'recurrence.days': 'day(s)',
    'recurrence.weeks': 'week(s)',
    'recurrence.months': 'month(s)',
    'recurrence.on_days': 'On days',
    'recurrence.monthly_mode': 'Monthly mode',
    'recurrence.on_day_n': 'On day',
    'recurrence.ends': 'Ends',
    'recurrence.never': 'Never',
    'recurrence.after_n': 'After N occurrences',
    'recurrence.on_date': 'On date',
    'settings.managed_by_tenant': 'Managed by tenant admin',
    'settings.hidden': 'Hidden',
    'settings.mobile_access': 'Mobile Access',
    'power.all_teachers': 'All Teachers',
    'power.all_types': 'All Types',
    'power.all_tags': 'All Tags',
    'teacher.all_categories': 'All Categories',
    'teacher.filter_position': 'Filter by Position',
    'teacher.filter_tag': 'Filter by Tag',
    'teacher.remove_position': 'Remove position',
    'teacher.select_from_list': 'Select from list...',
    'gantt.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.not_found': 'Not found',
    'common.sandbox': 'SANDBOX',
},
  'he-IL': {
    'app.title': 'מרכז המוזיקה אלפרט',
    'app.subtitle': 'מערכת ניהול',
    'nav.calendar': 'לוח שנה חכם',
    'nav.gantt': 'גאנט וחסימות',
    'nav.teachers': 'מורים',
    'nav.rooms': 'חדרים',
    'nav.lists': 'ניהול רשימות',
    'nav.manage': 'ניהול',
    'nav.financial': 'דשבורד פיננסי',
    'nav.settings': 'הגדרות',
    'nav.power_tools': 'כלים מתקדמים',
    'nav.analysis': 'ניתוח פיננסי',
    'nav.super_admin': 'מנהל-על',
    'nav.mobile_access': 'גישה מנייד',
    'ops': 'תפעול',
    'admin': 'ניהול',
    'analytics': 'אנליטיקה',
    'today': 'היום',
    // Buttons
    'btn.add': 'הוסף',
    'btn.create': 'צור',
    'btn.save': 'שמור',
    'btn.cancel': 'ביטול',
    'btn.delete': 'מחק',
    'btn.close': 'סגור',
    'btn.confirm': 'אישור',
    'btn.back': 'חזור',
    'btn.export': 'ייצוא',
    'btn.import': 'ייבא',
    'btn.clear_all': 'נקה הכל',
    'btn.sign_out': 'יציאה',
    'btn.connect_account': 'חבר את החשבון שלי',
    'btn.disconnect': 'נתק',
    'btn.reconnect': 'חבר מחדש',
    'btn.save_insight': 'שמור תובנה',
    'btn.download_report': 'הורד דוח (CSV)',
    // Calendar view
    'mode.day': 'יום',
    'mode.week': 'שבוע',
    'mode.month': 'חודש',
    'mode.list': 'רשימה',
    'filter.teacher': 'מורה: הכל',
    'filter.room': 'חדר: הכל',
    'filter.type': 'סוג: הכל',
    'filter.category_all': 'קטגוריה: הכל',
    'filter.no_filters': 'ללא פילטרים',
    'filter.show_canceled': 'הצג אירועים מבוטלים',
    'filter.show_blackouts': 'הצג חסימות',
    'filter.all_teachers': 'כל המורים',
    'filter.all_categories': 'כל הקטגוריות',
    'filter.all_types': 'כל הסוגים',
    'filter.all_tags': 'כל התגיות',
    'filter.by_position': 'סנן לפי תפקיד',
    'filter.by_tag': 'סנן לפי תגית',
    // Event modal
    'modal.add_event': 'הוסף אירוע',
    'modal.edit_event': 'ערוך אירוע',
    'label.name': 'שם האירוע',
    'label.desc': 'תיאור',
    'label.teacher': 'מורה',
    'label.room': 'חדר',
    'label.type': 'סוג',
    'label.start': 'התחלה',
    'label.end': 'סיום',
    'label.date': 'תאריך',
    'label.position': 'תפקיד',
    'label.recurrence': 'חזרתיות',
    'label.full_name': 'שם מלא',
    'label.teacher_color': 'צבע המורה',
    'label.category': 'קטגוריה',
    'label.rate_type': 'סוג תעריף',
    'label.room_name': 'שם החדר',
    'label.itinerary_desc': 'תיאור / ציוד',
    'label.from': 'מ-',
    'label.to': 'עד',
    'label.optional': '(אופציונלי)',
    'label.requires_teacher': '(דורש מורה ותפקיד)',
    'label.live': 'חי',
    'label.no_room': 'ללא חדר',
    'label.no_room_dash': '— ללא חדר —',
    // Calendar states
    'cal.canceled': 'מבוטל',
    'cal.no_events': 'אין אירועים',
    'cal.hide_canceled': 'הסתר מבוטלים',
    'cal.hide_blackouts': 'הסתר חסימות',
    'cal.recurring_event': 'אירוע מחזורי',
    'cal.every': 'כל',
    'cal.on_days': 'בימים',
    'cal.monthly_mode': 'מחזוריות חודשית',
    'cal.mark_canceled': 'סמן כמבוטל',
    'cal.cancel_pay_status': 'סטטוס תשלום ביטול',
    'cal.no_pay': 'ללא תשלום',
    'cal.paid_cancel': 'ביטול בתשלום',
    'cal.delete_event': 'מחק אירוע',
    'cal.payment_method': 'שיטת תשלום',
    'cal.select_category': 'בחר קטגוריה',
    'cal.save_changes': 'שמור שינויים',
    'cal.save_update_series': 'שמור ועדכן סדרה',
    'cal.update_this_only': 'עדכן רק את זה',
    'cal.update_all_future': 'עדכן את כל העתידיים',
    'cal.recurring_series_msg': 'זהו אירוע מתוך סדרה חוזרת. מה תרצה לעשות',
    'cal.this_event_only': 'אירוע זה בלבד',
    'cal.this_and_future': 'אירוע זה וכל הבאים',
    'cal.all_in_series': 'כל האירועים בסדרה',
    // Calendar recurrence
    'recurrence.none': 'ללא חזרה',
    'recurrence.daily': 'יומי',
    'recurrence.weekly': 'שבועי',
    'recurrence.biweekly': 'דו-שבועי',
    'recurrence.monthly': 'חודשי',
    'recurrence.yearly': 'שנתי',
    'recurrence.until': 'עד תאריך',
    'recurrence.ends_after': 'מסתיים לאחר',
    'recurrence.ends_on': 'מסתיים בתאריך',
    'recurrence.occurrences': 'מופעים',
    // Settings
    'settings.general': 'הגדרות כלליות',
    'settings.integrations': 'אינטגרציות',
    'settings.dev_tools': 'כלי מפתח',
    'settings.generate_data': 'יצירת נתוני בדיקה',
    'settings.generate_data_desc': 'אכלוס הלוח עם 20 מורים ואירועים אקראיים.',
    'settings.generate_btn': 'צור נתונים',
    'settings.unsaved': 'ישנם שינויים שלא נשמרו',
    'settings.testing_tools': 'כלי בדיקה',
    'settings.currency': 'מטבע',
    'settings.currency_symbol': 'סמל מטבע',
    'settings.currency_desc': 'סמל זה יופיע ליד כל ערכי העלות בדשבורד הפיננסי, הניתוח והייצוא.',
    'settings.gcal_sync': 'סנכרון יומן Google',
    'settings.gcal_desc': 'דחיפת שיעורים מתוזמנים ליומן Google של מנהל הארגון.',
    'settings.connected_via': 'מחובר דרך',
    'settings.sync_inactive': 'חשבון אחר — סנכרון לא פעיל עבורך',
    'settings.token_expired': 'אסימון האימות פג תוקף. חבר מחדש כדי לשחזר את הסנכרון.',
    'settings.fetching_cals': 'מביא את היומנים שלך...',
    'settings.select_calendar': 'בחר יומן יעד',
    'settings.choose_cal': '— בחר יומן —',
    'settings.primary': '(ראשי)',
    'settings.auto_add_desc': 'שיעורים חדשים יתווספו אוטומטית ליומן זה.',
    'settings.sync_managed_by': 'סנכרון היומן מנוהל על ידי {email}',
    'settings.sync_condition': 'אירועים יסתנכרנו ליומן Google רק כאשר המנהל ({email}) מחובר.',
    'settings.admin_only': 'מנהלים בלבד',
    'settings.managed_by_admin': 'מנוהל על ידי מנהל הארגון',
    'settings.week_hidden': 'מוסתר',
    'settings.week_number': 'מספר שבוע',
    'settings.week_of': 'שבוע של...',
    // Labels
    'label.default_lang': 'שפת מערכת',
    'label.system_default': 'ברירת מחדל של המערכת',
    'label.coming_soon': 'בקרוב',
    'label.timezone': 'אזור זמן',
    'label.date_format': 'פורמט תאריך',
    'label.time_format': 'פורמט שעה',
    'label.calendar_defaults': 'הגדרות יומן ברירת מחדל',
    'label.default_duration': 'משך אירוע ברירת מחדל (דקות)',
    'label.week_numbers': 'תצוגת מספרי שבועות',
    'label.blackout': 'חסימה',
    // Nav sections
    'nav.section.localization': 'לוקליזציה',
    'nav.section.date_time': 'תאריך ושעה',
    'nav.section.analytics': 'אנליטיקה',
    'nav.section.operations': 'תפעול',
    'nav.section.admin': 'ניהול',
    // Roles
    'role.admin': 'מנהל',
    'role.viewer': 'צופה',
    // Alerts
    'alert.confirm_generate': 'פעולה זו תדרוס מורים ואירועים קיימים. להמשיך?',
    'alert.data_generated': 'נתונים נוצרו בהצלחה!',
    'alert.delete_event': 'האם למחוק את האירוע?',
    'alert.delete_gantt': 'למחוק בלוק זה? הפעולה עשויה להשפיע על חסימות.',
    'alert.end_time_error': 'שעת הסיום חייבת להיות אחרי שעת ההתחלה',
    'alert.delete_teacher': 'האם למחוק מורה זה? אירועים קשורים יציגו אזהרות.',
    'alert.delete_room': 'האם אתה בטוח? אירועים מתוזמנים יציגו אזהרות.',
    'alert.delete_gantt_block': 'למחוק בלוק זה? אם זו חסימה, האירועים ישוחזרו.',
    'alert.error_reading_file': 'שגיאה בקריאת הקובץ',
    'alert.no_valid_teachers': 'לא נמצאו מורים תקינים או חדשים ב-CSV.',
    'alert.no_valid_rows': 'לא נמצאו שורות תקינות. ודא שהתאריכים בפורמט YYYY-MM-DD או DD/MM/YYYY.',
    'alert.csv_parse_fail': 'שגיאה בניתוח קובץ CSV.',
    'alert.delete_all_data': 'האם אתה בטוח שברצונך למחוק לצמיתות את כל הנתונים ממרחב העבודה הזה בענן?',
    'alert.action_cannot_undo': 'לא ניתן לבטל פעולה זו.',
    // Power Tools
    'pt.bulk_delete': 'מחיקה מרוכזת',
    'pt.date_range': 'טווח תאריכים',
    'pt.criteria': 'קריטריונים לסינון',
    'pt.preview': 'תצוגה מקדימה',
    'pt.delete_all': 'מחק הכל',
    'pt.confirm_delete': 'נא לאשר מחיקה של {count} אירועים.',
    'pt.success': 'נמחקו {count} אירועים בהצלחה.',
    'pt.no_matches': 'לא נמצאו אירועים מתאימים.',
    'pt.time_range': 'טווח זמן',
    'pt.interactive': 'בחירה אינטראקטיבית',
    'pt.import_csv': 'ייבוא מערכת שעות מ-CSV',
    // Financial Dashboard
    'fin.title': 'לוח בקרה פיננסי',
    'fin.all_time': 'כל הזמנים',
    'fin.grand_total': 'סה"כ כולל',
    'fin.hourly_fees': 'תעריפים שעתיים',
    'fin.global_monthly': 'חודשי גלובלי',
    'fin.active_hours': 'שעות פעילות',
    'fin.canceled': 'מבוטלים',
    'fin.teacher_metrics': 'מדדי מורים',
    'fin.sort_hint': '· לחץ על הכותרות למיון',
    'fin.current_week': 'השבוע הנוכחי',
    'fin.daily': 'יומי',
    'fin.hourly': 'שעתי',
    'fin.weekly': 'שבועי',
    'fin.monthly': 'חודשי',
    'fin.revenue_trend': 'מגמת הכנסות',
    // Table headers
    'col.name': 'שם',
    'col.active_hrs': 'שעות פעילות',
    'col.canceled_hrs': 'שעות מבוטלות',
    'col.cancel_count': 'מס\' ביטולים',
    'col.hourly_cost': 'עלות שעתית',
    'col.one_off_cost': 'עלות חד-פעמית',
    'col.global_cost': 'עלות גלובלית',
    'col.total': 'סה"כ',
    'col.recipient': 'נמען',
    'col.email_address': 'כתובת אימייל',
    'col.total_payout': 'סה"כ תשלום',
    'col.positions_rates': 'תפקידים ותעריפים',
    'col.contact': 'פרטי קשר',
    'col.rates': 'תעריפים',
    'col.entry_name': 'שם הרשומה',
    'col.actions': 'פעולות',
    // Financial Analysis
    'fin_ana.title': 'ניתוח פיננסי',
    'fin_ana.delete_chart': 'מחק תרשים',
    'fin_ana.insight_title': 'כותרת תובנה',
    'fin_ana.metric': 'מדד',
    'fin_ana.total_active_hours': 'סה"כ שעות פעילות',
    'fin_ana.total_canceled_hours': 'סה"כ שעות מבוטלות',
    'fin_ana.hourly_payroll': 'שכר שעתי',
    'fin_ana.global_payroll': 'שכר גלובלי',
    'fin_ana.grand_total_payroll': 'סה"כ שכר',
    'fin_ana.avg_hours_teacher': 'ממוצע שעות למורה',
    'fin_ana.avg_payroll_teacher': 'ממוצע שכר למורה',
    'fin_ana.cancel_rate': 'שיעור ביטולים',
    'fin_ana.highest_earner': 'המשתכר הגבוה',
    'fin_ana.lowest_earner': 'המשתכר הנמוך',
    'fin_ana.choose_insights': 'בחר תובנות לתצוגה',
    'fin_ana.no_insights': 'לא נבחרו תובנות. לחץ על ערוך כדי לבחור אילו תובנות להציג.',
    'fin_ana.create_first_chart': 'צור את התרשים המותאם הראשון שלך',
    'fin_ana.back_to_dashboard': 'חזרה לדשבורד',
    'fin_ana.classify_desc': 'קבץ נתונים לפי קטגוריה (טווחי זמן נשלטים בנפרד למטה)',
    'fin_ana.select_period_desc': 'בחר את תקופת הזמן לניתוח (ללא קשר להקבצה)',
    // Teacher Manager
    'teach.title': 'ניהול מורים',
    'teach.add': 'הוסף מורה',
    'teach.import_title': 'ייבוא מורים',
    'teach.import_csv': 'ייבוא מורים מקובץ CSV',
    'teach.csv_columns': 'בחר קובץ .csv עם העמודות: שם, אימייל, טלפון, תגיות',
    'teach.colors_auto': '* צבעים יוקצו אוטומטית',
    'teach.add_first_position': '+ הוסף תפקיד ראשון',
    'teach.position_assignment': 'שיוך תפקיד',
    'teach.select_to_import': 'בחר מורים לייבוא',
    'teach.unique_teachers': 'מורים ייחודיים. בחר את אלו שברצונך לייבוא.',
    'teach.selected': 'נבחרו',
    'teach.already_in_list': 'כבר ברשימה',
    'teach.skip': 'דלג',
    'teach.no_teachers_found': 'לא נמצאו מורים בקובץ זה.',
    'teach.back_to_list': 'חזרה לרשימה',
    // Room Manager
    'room.title': 'ניהול חדרים',
    'room.itinerary': 'ציוד ואביזרים',
    // Gantt
    'gantt.title': 'סמסטרים וחופשות',
    'gantt.subtitle': 'ניהול סמסטרים וחופשות.',
    'gantt.label_title': 'כותרת',
    'gantt.start_date': 'תאריך התחלה',
    'gantt.end_date': 'תאריך סיום',
    'gantt.display_color': 'צבע תצוגה',
    'gantt.apply_blackout': 'החל חסימה',
    'gantt.blackout_desc': 'הסתר אוטומטית את כל האירועים בטווח זה מהיומן ומהדוחות.',
    // Chart Builder
    'chart.title_label': 'כותרת התרשים',
    'chart.filter_mode': 'מצב סינון',
    'chart.live': 'חי',
    'chart.live_desc': 'מגיב לפילטרי הדשבורד',
    'chart.snapshot': 'תמונת מצב',
    'chart.snapshot_desc': 'מקפיא פילטרים בעת השמירה',
    'chart.sort_by': 'מיין לפי',
    'chart.dimension_label': 'תווית מימד',
    'chart.ascending': 'עולה',
    'chart.descending': 'יורד',
    'chart.no_options': 'אין אפשרויות זמינות',
    'chart.add_position': 'הוספת תפקיד',
    'chart.position_name': 'שם התפקיד',
    'chart.select_icon': 'בחר אייקון',
    'chart.choose_icon': 'בחר אייקון לתפקיד זה',
    // Filter sections
    'filter.teachers': 'מורים',
    'filter.positions': 'תפקידים',
    'filter.tags': 'תגיות',
    'filter.categories': 'קטגוריות',
    'filter.rate_type': 'סוג תעריף',
    // Manage Lists
    'lists.title': 'רשימות בחירה',
    'lists.desc': 'עדכן את האפליקציה שלך על ידי שינוי רשימות אלו.',
    'lists.classifications': 'סיווגים',
    'lists.how_to': 'איך להשתמש בכלי זה:',
    'lists.step1': '1. מלא את הנתונים למטה',
    'lists.step2': '2. ייצא ל-CSV',
    'lists.step3': '3. פתח באפליקציה שלך',
    'lists.add_row': 'הוסף שורה',
    'lists.template': 'תבנית',
    // Auth
    'auth.sign_in_google': 'התחבר עם Google',
    'auth.workspaces': 'סביבות עבודה מורשות',
    'auth.no_workspaces': 'לא נמצאו סביבות עבודה מורשות.',
    'auth.signing_in': 'מתחבר לענן Cadenza...',
    // Tooltips
    'tooltip.edit': 'ערוך',
    'tooltip.duplicate': 'שכפל',
    'tooltip.delete': 'מחק',
    'tooltip.switch_light': 'עבור למצב בהיר',
    'tooltip.switch_dark': 'עבור למצב כהה',
    'tooltip.expand_sidebar': 'הרחב תפריט צד',
    'tooltip.collapse_sidebar': 'כווץ תפריט צד',
    'tooltip.open_menu': 'פתח תפריט',
    'tooltip.add_event': 'לחץ להוספת אירוע',
    'tooltip.toggle_filters': 'הצג/הסתר פילטרים',
    'tooltip.remove_position': 'הסר תפקיד',
    // Placeholders
    'placeholder.search_teachers': 'חפש מורים...',
    'placeholder.or_type_new': 'או הקלד חדש...',
    'placeholder.event_name': 'לדוגמה: שיעור פסנתר',
    'placeholder.room_details': 'פרטים על ציוד, קיבולת וכדומה',
    'placeholder.choose_calendar': '— בחר יומן —',
    // Dynamic
    'dynamic.rate_hourly': 'תעריף ({currency}/שעה)',
    'dynamic.monthly_fee': 'דמי חודשי ({currency})',
    'dynamic.send_reports': 'שלח {n} דוחות',
    'dynamic.week_of': 'שבוע של {date}',
    'dynamic.hourly_currency': 'שעתי ({currency})',
    'dynamic.one_off_currency': 'חד-פעמי ({currency})',
    'dynamic.global_currency': 'גלובלי ({currency})',
    'dynamic.total_currency': 'סה"כ ({currency})',
    'dynamic.one_off_price': 'מחיר חד-פעמי ({currency})',
    // Footer
    'footer.copyright': '© 2026 מרכז המוזיקה',
    // Super Admin
    'super.title': 'מנהל-על',
    'super.delete_all': 'מחק את כל הנתונים',
  }
};

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'T1', fullName: 'John Smith',
    positions: ['Piano Instructor'],
    positionAssignments: [
      { id: 'T1_PA0', positionName: 'Piano Instructor', category: 'Individual Lesson', rateType: 'HOURLY', rateValue: 150 },
    ],
    tags: ['Piano Dept', 'Senior Staff'], phone: '555-0101', email: 'john@music.com', color: '#3b82f6'
  },
  {
    id: 'T2', fullName: 'Sarah Jones',
    positions: ['Voice Coach', 'Choir Director'],
    positionAssignments: [
      { id: 'T2_PA0', positionName: 'Voice Coach', category: 'Individual Lesson', rateType: 'HOURLY', rateValue: 120 },
      { id: 'T2_PA1', positionName: 'Choir Director', category: 'Group Lesson', rateType: 'GLOBAL_MONTHLY', rateValue: 5000 },
    ],
    tags: ['Vocal Dept'], phone: '555-0102', email: 'sarah@music.com', color: '#ef4444'
  },
  {
    id: 'T3', fullName: 'Michael Brown',
    positions: ['Violin Teacher'],
    positionAssignments: [
      { id: 'T3_PA0', positionName: 'Violin Teacher', category: 'Individual Lesson', rateType: 'HOURLY', rateValue: 130 },
    ],
    tags: ['Strings Dept'], phone: '555-0103', email: 'mike@music.com', color: '#10b981'
  },
];

export const INITIAL_ROOMS: Room[] = [
  { id: 'R1', name: 'Studio A', itinerary: 'Grand Piano, roughly 20 person capacity.' },
  { id: 'R2', name: 'Studio B', itinerary: 'Upright Piano, soundproofed.' },
  { id: 'R3', name: 'Practice Room 1', itinerary: 'Small room for individual practice.' },
];

export const INITIAL_RATE_CARDS: RateCard[] = [
  {
    id: 'RC_DEFAULT',
    versionId: 'V1',
    entries: [
      { id: 'RC_DEFAULT_E1', categoryId: 'individual_lesson', effectiveFrom: '2020-01-01', rateType: 'HOURLY', rateValue: 150 },
      { id: 'RC_DEFAULT_E2', categoryId: 'group_lesson', effectiveFrom: '2020-01-01', rateType: 'GLOBAL_MONTHLY', rateValue: 5000 },
      { id: 'RC_DEFAULT_E3', categoryId: 'rehearsal', effectiveFrom: '2020-01-01', rateType: 'HOURLY', rateValue: 100 },
    ]
  }
];

// Helper to generate some initial events relative to "today"
const today = new Date();
const getIso = (daysOffset: number, hour: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: 'E1',
    name: 'Piano Lesson - Alice',
    description: 'Weekly lesson',
    teacherId: 'T1',
    roomId: 'R1',
    positionId: 'T1_PA0',
    classification: Classification.INDIVIDUAL,
    start: getIso(0, 10),
    end: getIso(0, 11),
    isCanceled: false,
    isHidden: false,
  },
  {
    id: 'E2',
    name: 'Voice Coaching - Bob',
    description: 'Prep for recital',
    teacherId: 'T2',
    roomId: 'R2',
    positionId: 'T2_PA0',
    classification: Classification.INDIVIDUAL,
    start: getIso(0, 10), // INTENTIONAL CONFLICT with time, different room
    end: getIso(0, 11),
    isCanceled: false,
    isHidden: false,
  },
  {
    id: 'E3',
    name: 'Group Theory',
    description: 'Beginner theory',
    teacherId: 'T1', // INTENTIONAL CONFLICT: T1 is also in E1 at this time
    roomId: 'R3',
    positionId: 'T1_PA0',
    classification: Classification.GROUP,
    start: getIso(0, 10),
    end: getIso(0, 11),
    isCanceled: false,
    isHidden: false,
  }
];

export const INITIAL_GANTT: GanttBlock[] = [
  {
    id: 'G1',
    title: 'Winter Semester',
    startDate: new Date(today.getFullYear(), 0, 1).toISOString(),
    endDate: new Date(today.getFullYear(), 3, 30).toISOString(),
    color: '#3b82f6',
    isBlackout: false,
  }
];

export const generateId = () => Math.random().toString(36).substr(2, 9);

export const formatDateForInput = (isoString: string) => {
  if (!isoString) return '';
  const date = new Date(isoString);
  const offset = date.getTimezoneOffset();
  const localDate = new Date(date.getTime() - (offset * 60 * 1000));
  return localDate.toISOString().slice(0, 16);
};

export const formatDate = (date: Date, format: string) => {
  const d = date.getDate().toString().padStart(2, '0');
  const m = (date.getMonth() + 1).toString().padStart(2, '0');
  const y = date.getFullYear();

  switch (format) {
    case 'DD/MM/YYYY': return `${d}/${m}/${y}`;
    case 'YYYY-MM-DD': return `${y}-${m}-${d}`;
    default: return `${m}/${d}/${y}`; // MM/DD/YYYY
  }
};
